### ISSUE TITLE
S3 storage?

### ISSUE THREAD

**Issue by alicam** [tom472/mediabox#10]
So it's got Minio...

Does that mean I can run up a cheap VM on Digitalocean but access loads of storage on S3? Can I download and "post-process" stuff to the server, but then save to and serve from S3?

If not be default, how might that be accomplished?

**Comment by tom472** [comment]
While yes this has Minio and it is a great S3 compatible storage option I may be changing that soon.
I have been looking a possibly swapping Minio for Pydio.
Just looking for an easy front-end for the files within the project should users need to do any file/folder manipulation.

But yes - if you have access to a large amount of local storage you can certainly use Minio to front-end the access to that storage.
 
The important part of the Minio container for that is the "Volumes" section:    
<pre>
volumes:
    - '${PWD}:/export'
    command: server /export
</pre>
Just change / switch the `${PWD}` local folder to the mount point of you storage location.
