### ISSUE TITLE
Issue with Jackett page

### ISSUE THREAD

**Issue by nfields03** [tom472/mediabox#102]
I was just noticing the other day that my connection to Jackett in Mediabox stopped working through the menu. When I click on it, I get "SERVERIP redirected you too many times." When I go to the manual page for Jacket though I can see that the container is running just fine (http://SERVERIP:9117/UI/Dashboard works perfectly). Mediabox as a whole is still running great, thanks for all that you do!

**Comment by tom472** [comment]
@nfields03 -- thanks for the report I'll have to look into it.
I myself am currently not able to reproduce the issue at the moment.

Hopefully if anyone else is having the issue they'll jump in this thread.

Also have you tried clearing your cache and/or trying to hit the Mediabox main page via a private/incognito window?

**Comment by nfields03** [comment]
Hmm, cleared cache but same result. Tried incognito window, same result. Tried multiple browsers (Edge, Chrome, Firefox), no change. I'll keep digging since you can't repro and see if I can find some commonality. I've got a test VM on another host to try in my lab this week, just wanted to see if anyone else is running into the issue.

**Comment by nfields03** [comment]
Still no luck on this, same error from the other test VM. I'm loathe to wipe and rebuild the whole setup but I might do so today just to make sure everything is running as clean as possible as I ran into a weird issue when setting up nzbget as well. If that persists past the rebuild, I'll log it as a separate issue.

**Comment by tom472** [comment]
@nfields03  -- Are you still having this issue? I am still unable to replicate it ..

**Comment by nfields03** [comment]
Sorry, it stopped happening for me as well so you're welcome to close it
out.

Cheers,

Nick
