### ISSUE TITLE
Ubuntu 20.04 LTS support

### ISSUE THREAD

**Issue by rudolph4404** [tom472/mediabox#104]
Is Ubuntu 20.04 LTS supported?

**Comment by tom472** [comment]
@rudolph4404 There's no real reason it shouldn't work. I haven't had a minute to actually test a deploy on 20.04.
Generally anyone already on the previous LTS i.e. 18.04 will not be notified of the next LTS until that hits it's xx.xx.1 release.
So I'll give it a shot on my VPS if I get a chance to but I can't think of any real showstoppers.

Tom

**Comment by edorexy** [comment]
ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/lib/gconv/IBM1371.so: no space left on device

**Comment by tom472** [comment]
@edorexy Where about in the process did this happen? And was this on an upgraded system already running Mediabox or a fresh 20.04 system and new install?

**Comment by edorexy** [comment]
Fresh install, just about the point of launching the media server after the last docker pull

**Comment by tom472** [comment]
20.04 has had some successful installs and upgrades -- 
Any luck?

**Comment by edorexy** [comment]
> 20.04 has had some successful installs and upgrades --
> Any luck?

YES, It Worked great
