### ISSUE TITLE
Issues with completing mediabox.sh on Raspberry Pi swarm (Indefinitely Pausing)

### ISSUE THREAD

**Issue by KN4KNG** [tom472/mediabox#105]
At the end of the set-up mediabox.sh script it indefinitely pauses at:

You need to set a username and password for a of the programs - including.
The Deluge daemon, NZBGet's API & web interface, and Minio.
What would you like to use as the access username?: username
What would you like to use as the access password?: password

Configuring DelugeVPN, NZBGet, Muximux, and Permissions
This may take a few minutes...

After reviewing [Issue #72](https://github.com/tom472/mediabox/issues/72) I retried with making sure all entries were completed, additionally I know PIA has had issues with Raspberry Pi users and having to manually set name severs. In most of my other builds PIA has had no issue working fllowing [This Guide](https://www.privateinternetaccess.com/helpdesk/kb/articles/how-to-use-pia-dns-with-your-raspberry-pi). I have attempted setting the nameservers per link and leaving at default. 

I can see the port published on all containers except deluge, jellyfin, minio, ourobros in portainer deluge shows that it is running and the credentials for PIA are correct.  

Few other notes:
I have not deployed the stack to the swarm yet. 
All .ovpn files are correct.
PIA Username & Password verified correct via another RPi set-up.

I am still leaning towards PIA and Raspbian not getting along as the culprit but I am stuck with trying to resolve. 

I understand that this was not originally designed for Raspberry Pi, (and according to composer Swarms either) but I have a bunch of hardware laying around begging for attention. Any assistance will be greatly appreciated. 

Edit: I am not sure if the PIA issue is OS related or Architecture related, I will reattempt on another Raspberry Pi OS as good measure. I have been documenting the minor changes for the RPi set up, if you'd like I can share to allow update of the README.md.

**Comment by tom472** [comment]
Raspberry Pi is not the target for this project.
