### ISSUE TITLE
remove programs from install

### ISSUE THREAD

**Issue by Twonkk** [tom472/mediabox#108]
hey, was wondering if its possible to remove some programs from the install script? i really only need the CouchPatato, Deluge and plex (and PIA)?

also, works great in a VM Ubuntu Server 20.04

**Comment by tom472** [comment]
The simplest way is to just use Portainer after the set-up is done and just"stop" the containers you don't want/need.
Docker will remember those are stopped and will not restart them back up later on.

Also - Thanks for the info re: Ubuntu Server 20.04 -- 
I had just started some testing on an "upgraded" 18.04 to 20.04 and that was fine.
Was your Server 20.04 a fresh install of that version?

**Comment by Twonkk** [comment]
> The simplest way is to just use Portainer after the set-up is done and just"stop" the containers you don't want/need.
> Docker will remember those are stopped and will not restart them back up later on.
> 
> Also - Thanks for the info re: Ubuntu Server 20.04 --
> I had just started some testing on an "upgraded" 18.04 to 20.04 and that was fine.
> Was your Server 20.04 a fresh install of that version?

@tom472 

I apologize for the late response, been a long week. both the test VM (always test first :P ) and the actual deploy to my home server had been fresh 20.04 installs and neither had issues with installing.

**Comment by tom472** [comment]
@Twonkk -- While yes there are ways to do SSL/Port Forwarding - I generally do not cover those here.
While sure it's "cool" to have access to Muximux and/or the other interfaces while outside your network.
Aside from PLEX there really isn't a "need" for access to the others.

And then setting up configs for this comes in way to many ways to kind of be able to support.
My simple recommendation is to just set-up a VPN on your internal network and then just VPN to you home network if/when you want to access one of the other items.

And thanks again for the info on your 20.04 installs!
