### ISSUE TITLE
deluge UI no longer accessible

### ISSUE THREAD

**Issue by willstoeckel** [tom472/mediabox#109]
I'm getting a refused to connect error when trying to launch the deluge UI. I verified I had the latest code with a git pull and reran the mediabox.sh script. I tried selecting a different openvpn server as well. I checked that the process is running and there is a listener on tcp 8112. Platform is Ubuntu 18.04.5 LTS. Let me know if there any specific log files I can attach.

**Comment by Bramblefoot** [comment]
Look specifically at the logs for that container in portainer. Whenever
deluge goes down for me, it's PIA and their exit node not port forwarding
properly.
Hope this helps.

Bill
"Try not. Do, or do not. There is no try." - Yoda

**Comment by willstoeckel** [comment]
Thanks Bill. Did some digging and it does look like it's an issue with the PIA node. Maybe I'll see if I can manually edit or use their auto-generated config file.
,
2020-09-19 16:55:54,904 DEBG 'start-script' stdout output:,
[warn] Exit code '56' from curl != 0 or no response body received,
[info] 1 retries left,
[info] Retrying in 10 secs...,
,
2020-09-19 16:56:06,260 DEBG 'start-script' stdout output:,
[warn] Exit code '56' from curl != 0 or no response body received, exhausted retries,
[warn] Unable to download file from url 'http://209.222.18.222:2000/?client_id=2cb92b3fde49aed2174fe48bd10079f6fcd85ff82a469a66103f18d7fe2cb7d1', exiting script...,
,
2020-09-19 16:56:06,260 DEBG 'start-script' stdout output:,
[warn] PIA VPN port assignment API currently down, terminating OpenVPN process to force retry for incoming port...,
,
2020-09-19 16:56:06,261 DEBG 'start-script' stdout output:,
Sat Sep 19 16:56:06 2020 event_wait : Interrupted system call (code=4),
,
2020-09-19 16:56:06,267 DEBG 'start-script' stdout output:,
Sat Sep 19 16:56:06 2020 /usr/bin/ip addr del dev tun0 local 10.61.11.6 peer 10.61.11.5,
,
2020-09-19 16:56:06,286 DEBG 'start-script' stdout output:,
Sat Sep 19 16:56:06 2020 SIGINT[hard,] received, process exiting,
,
2020-09-19 16:56:14,259 DEBG 'start-script' stdout output:,
[warn] OpenVPN process terminated, restarting OpenVPN...,

**Comment by willstoeckel** [comment]
The only way I was able to get this to work was to edit the docker-compose.yml file and set VPN_ENABLED=no in the deluge section. I can use PIA VPN on the server itself but then that breaks the plex remote access. I'd rather just keep it split-tunneled to deluge if possible.

**Comment by Bramblefoot** [comment]
In my experience, It's just a reality with PIA. Their port forwarding goes
down occasionally. And when that happens it affects deluge. I've found no
solution and just have to ride it out when it happens. And once the PIA
port forwarding comes back up, deluge just starts working again.
Fortunately I rely more on usenet than torrents.

Good luck.
Bill

"Try not. Do, or do not. There is no try." - Yoda

**Comment by willstoeckel** [comment]
Thanks Bill. I found this update from PIA so it does look like it's the port forwarding. Leaving it here in case anyone else comes along with the same problem:
https://www.privateinternetaccess.com/helpdesk/news/posts/important-updated-server-changes-and-related-issues

**Comment by tom472** [comment]
Just an FYI - for all -- 
You can easily re-run `.\mediabox/sh` to choose / select a different PIA server when a location is having a Port-Forward issue.
