### ISSUE TITLE
Request - Add FFmpeg or HandbrakeCLI

### ISSUE THREAD

**Issue by archshift2** [tom472/mediabox#110]
Consider adding ffmpeg or handbrakecli as a docker container in order to support Plex DVR post-processing scripts.

**Comment by tom472** [comment]
I can look into this - do you happen to have any links to specific containers or any write ups on the topic?
Thanks

**Comment by archshift2** [comment]
I had attempted to modify my setup with a separate handbrake docker based on a plex forum I came across. Since it is a separate container, a watch folder strategy would be needed.
[https://forums.plex.tv/t/plex-dvr-linux-docker-post-processing-script-using-handbrake-to-compress-video-and-retaining-close-caption/492673](url)

Since the encoder would really only be used for DVR post processing, it seems like a better approach might be to integrate with a plex container instead of create a separate install and watch folder scheme.
[https://www.reddit.com/r/unRAID/comments/81l0j8/in_case_anyone_needs_it_ive_created_a_plex_media/](url)

I just stumbled across the second option as I was trying to find a solution. It looks promising and could be integrated into the setup script with a transcoding choice which will select the approach docker image. I might test the alternative docker image to see how it works out.

**Comment by archshift2** [comment]
There is a way to invoke the built-in Plex encoder. I was able to download the script below and post-processing was successful.
[https://github.com/cedarrapidsboy/pms-postprocessing](url)

Suggest marking closed given the specific nature of this request.
