### ISSUE TITLE
PIA mandatory update

### ISSUE THREAD

**Issue by rudolph4404** [tom472/mediabox#111]
Have you seen this yet?
https://www.privateinternetaccess.com/blog/private-internet-access-legacy-vpn-network-sunset-announcement-30-september/

Will rerunning mediabox.sh update PIA?

**Comment by tom472** [comment]
I have seen the announcement and need to look into the impact / effect on Mediabox.
Stay tuned - 

Thanks

**Comment by tom472** [comment]
OK .. I have looked into the latest info on the deluge-vpn container and the maintainer of that has adjusted for the next-gen PIA network.
There are some configuration adjustments that I need to make but I should have this incorporated into Mediabox during this weekend.

**Comment by tom472** [comment]
OK as of commit https://github.com/tom472/mediabox/commit/732d14457b48aee56f86341d0c0c846c21a8b245 Mediabox should configured for using the PIA Net-Gen Network.
All that should be needed is to re-run the `./mediabox.sh` script.

I'll leave this issue open for a few more days for any issues but this should be good to go.

Thanks
--Tom

**Comment by taylorscape7** [comment]
> 
> 
> OK as of commit [732d144](https://github.com/tom472/mediabox/commit/732d14457b48aee56f86341d0c0c846c21a8b245) Mediabox should configured for using the PIA Net-Gen Network.
> All that should be needed is to re-run the `./mediabox.sh` script.
> 
> I'll leave this issue open for a few more days for any issues but this should be good to go.
> 
> Thanks
> --Tom
Hello Tom,

I attempted to update the script after I had a storage failure and the deluge : 1198 is refusing to open. I destroyed the VirtualBox and restored the original copy that had a working Deluge and it was opening via web interface. I updated the script and again I'm unable to access the interface. I'm trying to make sense of the error log and would love some help. If need be I can copy the log file from the server but I'll try and TLDR it. I've attempted to delete the delugevpn folder and portainer delugevpn stopped and destroyed, ran script again inserted PIA credentials on script and same issue.

```
Attempting to load tun kernel module...
start-script error: stderr output: modprobe: FATAL: Module tun not found in directory /lib/modules/5.4.0-48generic
Unable to load tun kernel module using modprobe, trying insmod...
insmod: ERROR: could not load module /lib/modules/tun.ko: No such file or directory
AUTH: Received control message: AUTH_FAILED
WARNING: file credentials.conf is group or others accessible
```

Ubuntu 18.04.5 LTS 64-bit
OpenVPN 2.4.9
Mediabox 3.5

Cheers!
