### ISSUE TITLE
Possibility of adding NZBHydra2

### ISSUE THREAD

**Issue by Bramblefoot** [tom472/mediabox#112]
I'm hoping we can get NzbHydra2 or Hydra2 added to the stack. I'm not exactly sure what the difference is between them, but they are both in Linuxserver.io. I feel it can be a useful tool since all your indexers can be centralized in 1 container. If you decide it's worth adding, I'm sure you will decide which one is "better" than the other.

Thanks,
Bill

**Comment by tom472** [comment]
OK -- I'll take a look at them and see if I can get one added.
Many of the container's are already Linuxserver.io so adding another one of theirs is usually pretty easy.
Thanks for the suggestion ..

**Comment by jeffjarratt** [comment]
I too would find this feature useful.

**Comment by tom472** [comment]
OK as of commit 882f7bd56f9736cdba1e62c76c9783ccedb3b9fe NZBHydra2 has been added to Mediabox
Please let me know if you have issues with it.

**Comment by Bramblefoot** [comment]
Thanks for adding nzbhydra2. The only thing I noticed is I don't think it's
being added as a button in muximux.
If you decide to get it added to muximux, there is an icon for it. I find
it on the 11th page of that little icon selection pop-up.

Thanks,
Bill

"Try not. Do, or do not. There is no try." - Yoda

**Comment by tom472** [comment]
Make you you have fully updated Mediabox - you might have caught a brief window when I had duplicated an existing icon when adding NZBHydra2 to Muximux -- also make sure cache is cleared for the Muximux page -- there is an icon for it in Muximux for sure - but it was incorrect for a small window.
