### ISSUE TITLE
Muximux stops responding

### ISSUE THREAD

**Issue by cfaber01** [tom472/mediabox#115]
Have you had any occurrences where muximux will stop responding? This has happened on several rebuilds and restarting the container does not work. Rerunning the script does work, but it resets some env variables that I have custom set. Any ideas?

**Comment by tom472** [comment]
I have not had any issues with that .. 
When you say stops responding does that mean the Muximux page itself doesn't load or the redirects stop working?
Does anything appear in that log for Muximux when this happens?

Also what are custom setting is the `.env` file?
Is is something that I could/should add to the `.env` file?

**Comment by cfaber01** [comment]
The page stops responding on port 80. The logs show the service as up and running (no errors). Browsing to the ip or fqdn displays “page cannot be displayed”. Navigating to the proper ip:port does work for the intended services (minus 80). I’ve recreated and restarted the container several times. Rerunning the script will restore, but also reverts env settings that I have custom. Nothing that should be included in the .env for the masses, just some custom images I have running on the same host.

**Comment by tom472** [comment]
OK -- I'll look into it if I can ... I have also been looking into other landing pages this weekend too.
So if you happen to have any suggestions let me know.

The issue doesn't happen to be like bad cache or anything like that does it? When it is happening if you go to the page in a private/incognito tab does it still not open? -- Just a thought -- 

And thanks again!

**Comment by cfaber01** [comment]
Correct, tried other browsers and incognito in Chrome with all the same result.

**Comment by tom472** [comment]
@cfaber01  -- There has been a Mediabox update - have you run that and seen if this issue is still happening?
