### ISSUE TITLE
Media request app Overseerr

### ISSUE THREAD

**Issue by Bramblefoot** [tom472/mediabox#117]
This is Not an issue...
Tom, 
I was recently turned onto this new media request app called Overseerr. You may have also heard of it. If not I highly recommend you spin up a container of it. Unfortunately it is alpha software currently, but I like it much better than OMBI. Check it out and see what you think. It's good looking and easy to use.

**Comment by tom472** [comment]
OK - I'll take a look into it and see how it looks/works.
Thanks for the recommendation ..

**Comment by tom472** [comment]
Hey @Bramblefoot -- as of commit https://github.com/tom472/mediabox/commit/8599e8a3b422bbc61dd9baff9368bc0099c59a98 Overseerr has been added to Mediabox.
Go ahead and update and see how it works our for you.
I'll leave this Issue open for a bit more..
Thanks again for the suggestion

--Tom

**Comment by tom472** [comment]
Closing issue now - container has been added and seems to be stable.
--Tom
