### ISSUE TITLE
Plex Volumes Error

### ISSUE THREAD

**Issue by archshift2** [tom472/mediabox#118]
Latest docker-compose.yml appears to have an error for the plex container.

Previous setup:
            - '${MISCDIR}:/data/misc'
            - '${MOVIEDIR}:/data/movies'
            - '${MUSICDIR}:/data/music'
            - '${TVDIR}:/data/tvshows'

Current setup:
            - '${MISCDIR}:/data/misc'
            - '${MOVIEDIR}:/data/movies'
            - '${MUSICDIR}:/data/music'
            - '${TVDIR}:/media/tv'

All content is referenced to /data except for tv. Appears to be a copy/paste error. Inconsistent location of /media instead of /data.

**Comment by tom472** [comment]
Thanks for catching that -- yeah copy paste can bite ya sometimes ..
I went through and put the volume mappings in Alpha order - and must have pasted the Plex TV one from the Tdarr config.
Fixed via commit https://github.com/tom472/mediabox/commit/1f60683e3acea1ec1548e469bedce33a897e2a88 please update and test.

Thanks again @archshift2 !!

**Comment by archshift2** [comment]
commit 1f60683 changed to '/data/tv'. needs to be '/data/tvshows' to continue working with prior installs.

**Comment by tom472** [comment]
Wow I must really need some coffee!!
Let's try commit https://github.com/tom472/mediabox/commit/d77679db683832ffa601f1262f71d344d45bfe51 as a fix ...
Thanks @archshift2 -- Really appreciate you catching this .. Twice!

**Comment by archshift2** [comment]
Back up and running. Thanks @tom472
