### ISSUE TITLE
Video Size Compression

### ISSUE THREAD

**Issue by RickyxNguyen** [tom472/mediabox#119]
I have been using this for quite a while and have been running out of space recently. Is there a way you can add Sickbeard MP4 Automator and Handbrake to reduce the file size but preserve the quality?

**Comment by tom472** [comment]
I can look into this - and see what I can do.
However in the meantime - Tdarr was recently added and I believe that application should have this functionality available in it.
Have you looked into trying that to accomplish this?

I'll be honest I don't make use of Tdarr myself but it should be able to help with this.
But I'll also take a look into the item(s) you mentioned as well.
--Tom

**Comment by RickyxNguyen** [comment]
I did not notice the new update so I will definitely try tdarr.

**Comment by tom472** [comment]
Hey @RickyxNguyen -- Just want to verify 
Was Tdarr able to accomplish what you needed?
Just want to make sure I won't need to look into the options you mentioned at the top of the thread,

And thanks for using Mediabox 
--Tom

**Comment by RickyxNguyen** [comment]
Yes it did it works great

**Comment by tom472** [comment]
OK excellent!

Thanks again.
