### ISSUE TITLE
Requestrr 

### ISSUE THREAD

**Issue by RickyxNguyen** [tom472/mediabox#120]
I saw a new api called requesterr where you can request shows and movies from discord and I found it could be really time saving since you could do this in your phone. A possible feature enhancement?

**Comment by tom472** [comment]
This looks pretty cool and the fine folks over at LinuxServer.io do appear to have a container for this.
So in theory - this should be relatively easy to roll in to Mediabox.
Time permitting - I'll try and add this in over the weekend.

Thanks for the suggestion

**Comment by tom472** [comment]
@RickyxNguyen 
OK with commit https://github.com/tom472/mediabox/commit/f35598143ad2bb84b0a2028e371bc12d5d3e4c6f Requestrr has been added to Mediabox.
Please give it some testing and let me knwo how it goes.

Thanks
--Tom

**Comment by RickyxNguyen** [comment]
Will do and will let you know if there are any problems

**Comment by tom472** [comment]
Any update on this? 
Does this appear to be working?

**Comment by tom472** [comment]
Gonna close this as the service has been successfully added -- if anyone has issues using the container please open a fresh issue.
