### ISSUE TITLE
NZBGet

### ISSUE THREAD

**Issue by RickyxNguyen** [tom472/mediabox#121]
When downloading a show Sonarr can’t pick up the download after it finishes

**Comment by RickyxNguyen** [comment]
Only occurs when using usenet

**Comment by tom472** [comment]
Hmm -- I have no way to test that - no usenet access.
But I'll recheck the folder mappings and make sure they have the correct entries.

**Comment by tom472** [comment]
So I did some checking to lay it out:

The docker-compose  file maps this volume for NZBGet: `${DLDIR}:/downloads`  
`${DLDIR}` should equate to `[path]/mediabox/content`

NGBGet has **MainDir**: Root directory for all tasks.  
`/downloads` so from above would equate to `[path]/mediabox/content`  

Then has **DestDir**: Destination directory for downloaded files.   
`${MainDir}/completed` which would equate to `[path]/mediabox/content/completed`

Then has **InterDir**: Directory to store intermediate files  
`${MainDir}/incomplete` which would equate to `[path]/mediabox/content/incomplete`
  

Sonarr has this volume mapped in the docker-compose file: `${DLDIR}/completed:/data/completed`  
Which again equates to: `[path]/mediabox/content/completed`

  
So all of the path mappings appear to match up and be correct -- Are the files ending up anywhere?  
Like still sitting in:  
`[path]/mediabox/content/incomplete`  
or  
`[path]/mediabox/content/completed`

Also -- anything showing in the logs for NZBGet?  

Let me know - Hope we can figure this out.

**Comment by tom472** [comment]
OK so NZBGet appears to be doing the correct steps and getting completed downloads to the completed folder.  
Are there any errors in the Sonarr logs related to post-processing for getting the items to the TV folder?

**Comment by archshift2** [comment]
There are some inconsistencies in the yml file. Some of the directories use /downloads some use /data and some use /media. It would be nice to re-write the yml file and be consistence across all the platforms, but unfortunately an update like that would break everyone existing install base. There is a way to fix this within sonarr, add a remote path mapping in the download client section.

Remote Path: /downloads/completed/
Local Path: /data/completed/

You might also want to consider using the category tag within sonarr & radarr to help them from stay organized (same with deluge as well).

**Comment by tom472** [comment]
@RickyxNguyen -- any chance the recommendation from @archshift2 helps/helped with the issue?

**Comment by RickyxNguyen** [comment]
I haven’t had the chance to try it out yet but I will let you know the minute I get it done

**Comment by RickyxNguyen** [comment]
Worked perfectly

**Comment by tom472** [comment]
Excellent .. thanks!
