### ISSUE TITLE
running script on new install of ubuntu stuck....

### ISSUE THREAD

**Issue by crusie** [tom472/mediabox#125]
I get to install the whole thing but when it goes to 

Configuring DelugeVPN, NZBGet, Muximux, and Permissions
This may take a few minutes...

it just stops - is there a log I can look at to see what goes wrong ?

**Comment by crusie** [comment]
hmm seems it was a permission error. I just tried fixing permissions and the script chugs along - Would have been nice if the script had thrown out an error instead of just stopping though

**Comment by tom472** [comment]
@crusie - What permissions did you have to fix?
I can try and add an error check but I'd need to know more about what you needed to adjust to then account for that.

**Comment by willstoeckel** [comment]
i'm having this same problem. any idea what permissions needed to be changed?

**Comment by tom472** [comment]
@willstoeckel - Are you still having this issue?
This is on a new configuration and is stopping at this step?
`Configuring DelugeVPN and Permissions`
`This may take a few minutes...`

**Comment by willstoeckel** [comment]
Not currently - I tore everything down and started over. I'll let you know if I encounter it again. It was a fresh 20.04 LTS install though.
