### ISSUE TITLE
DelugeVPN fails to complete startup

### ISSUE THREAD

**Issue by rjpete516** [tom472/mediabox#126]
I just made some changes to things on my system and I re-ran the mediabox script.  The script finishes and the containers start up, but DelugeVPN does not establish it's VPN.  All other containers appear to be functional, but can not communicate with Deluge.

From the Log accessed via Portainer:

> 2021-11-15 14:24:06,536 DEBG 'start-script' stdout output:,
> parse error: Invalid numeric literal at line 2, column 0,
> ,
> 2021-11-15 14:24:06,537 DEBG 'start-script' stdout output:,
> [warn] Unable to successfully download PIA json to generate token from URL 'https://privateinternetaccess.com/gtoken/generateToken',
> [info] 12 retries left,
> [info] Retrying in 10 secs...,

Where do I go from here?

Thanks,

Rob

**Comment by tom472** [comment]
@rjpete516 -- This could possibly be a momentary issue with the PIA endpoint you have currently selected.
Can you try running the script again and pick a different PIA endpoint and see if there is any change?

Also - apologies for needing to re-run the script to change the PIA endpoint.
Having a way to change the PIA selection easier / on the fly is on my To Do list.

Let me know

--Tom

**Comment by rjpete516** [comment]
That did the trick.  I thought I had tried switching to a different endpoint.  Maybe they were having issues on multiple endpoints. 

 Thanks,

Rob
