### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by nickelnine** [tom472/mediabox#127]
Hi - been using this service for a while, it is a great piece of work. I ran mediabox.sh tonight because Deluge was giving me some problem that I was not able to fix so thought an update might help. Now after running the script several times I'm faced with a different problem of - `404 page not found` - when going to my server IP address.

The last I used this script was on a 1.x release when Muximux was the front end (which now has changed to Homer). I'm excited to see what kind of changes are in store but really need to get this page launched.

Any help is appreciated. I've verified the .env file as well as all containers have started up successfully.

Edit: Based on #122, I can access Minio (login doesn't work) but not main landing page
Edit 2: I can manually reach Muximux on port 8080 but Deluge doesn't connect, nor does TubeSync. Radarr and Sonnar connect but the main Mediabox tab is also a 404 not found

**Comment by tom472** [comment]
Ah -- sorry that you are having an issue -- 

Couple things to try:
1 - Can you try reaching the main page using an incognito/private browser tab/instance?
Sometimes the switch to different landing pages can lead to cache/cookie issues.

2 - Can you reach Portainer via `ip_address:9000` and check the status of the containers?
To see which ones are up / down / showing issues etc. just to get a feel for which containers may not be starting.

**Comment by nickelnine** [comment]
1) No luck in reaching the landing page via incognito window - same `404 page not found` error
2) I can reach Portainer and all containers are up and running. The Homer container has this in the logs which I assume is okay:
`127.0.0.1 - - [01/Mar/2022:16:04:15 +0000] "GET / HTTP/1.1" 200 3230 "" "Wget"`

**Comment by nickelnine** [comment]
Found the issue. Another service I have is using port 80. I stopped that service and Homer now launches.

My initial Deluge issue still persists though, I will open another issue for it.
