### ISSUE TITLE
New Portainer

### ISSUE THREAD

**Issue by Bramblefoot** [tom472/mediabox#131]
Sorry if this is a stupid question but I'm not an expert with certificates.
I'm wondering, since this new Portainer is now using HTTPS and an IP address, will I need a self signed certificate? 
I already have a Let's Encrypt wildcard cert for 2 websites running on my server. 1 website is not associated with anything mediabox, but the other does point to a couple apps, reverse proxied, I allow outside users to access. Portainer is not exposed to the outside.
If I use Homer to access Portainer I see that I get the standard "Potential Security Risk/Connection isn't private" warnings.
And I did notice in portainer that there is some SSL Certificate section.
Is it possible to have 1 CA signed cert for my websites, and a self signed cert for portainer on the 192.168 network?
Think making and setting up a cert for portainer could be a function of the mediabox.sh script?
Also, I'm finding that the link in Muximux doesn't work for Portainer anymore.
(anything to do with loading an https page in a frame?)

Any help/info is appreciated,
Bill

**Comment by tom472** [comment]
I can reach the Portainer page from Muximux however the authentication does not seem to complete.
Likely not going to address as I think I will pulling Muximux from Mediabox as that project does not appear to be actively developed anymore.
