### ISSUE TITLE
Portainer not found

### ISSUE THREAD

**Issue by nickelnine** [tom472/mediabox#133]
Good evening,

I updated mediabox to 2.10 and now Portainer is not loading at all. I'm not running SSL so trying to reach it on port 8000 but I keep receiving a 'Not Found' message. I've run the script many times, deleted the Portainer container and folder but to no avail.

Any suggestions?

Thanks!

**Comment by Bramblefoot** [comment]
Portainer UI is now served over port 9443.

Try that.

Thanks,
Bill

**Comment by tom472** [comment]
@Bramblefoot  -- Is correct 
Both the Homer and Muximux start pages should be directing to https://hostname:9443 now.
Did those not update for you?

**Comment by nickelnine** [comment]
User error. It's all good now and everything is loading properly. Thanks for the great work on this project.
