### ISSUE TITLE
Deluge losing connection

### ISSUE THREAD

**Issue by nickelnine** [tom472/mediabox#135]
The connection closes intermittently but I haven't been able to clearly identify from the logs why it's losing connection but it seems tied to possibly a couple of things:
https://forums.unraid.net/topic/44109-support-binhex-delugevpn/page/369/
https://www.reddit.com/r/mullvadvpn/comments/wdch5d/deluge_drops_all_connections_after_a_few_minutes/
https://www.reddit.com/r/unRAID/comments/rg3qmm/delugevpn_has_anyone_had_disconnection_issues/

Here is a snippet from the logs:
`2022-12-09 09:00:35,727 DEBG 'watchdog-script' stderr output:
malloc(): invalid next size (unsorted)
2022-12-09 09:01:04,347 DEBG 'watchdog-script' stdout output:
[info] Deluge not running
2022-12-09 09:01:04,362 DEBG 'watchdog-script' stdout output:
[info] Attempting to start Deluge...
[info] Removing deluge pid file (if it exists)...
2022-12-09 09:01:04,777 DEBG 'watchdog-script' stdout output:
[info] Deluge key 'listen_interface' currently has a value of '10.26.112.129'
[info] Deluge key 'listen_interface' will have a new value '10.26.112.129'
[info] Writing changes to Deluge config file '/config/core.conf'...
2022-12-09 09:01:05,215 DEBG 'watchdog-script' stdout output:
[info] Deluge key 'outgoing_interface' currently has a value of 'tun0'
[info] Deluge key 'outgoing_interface' will have a new value 'tun0'
[info] Writing changes to Deluge config file '/config/core.conf'...
2022-12-09 09:01:05,633 DEBG 'watchdog-script' stdout output:
[info] Deluge key 'default_daemon' currently has a value of 'b79a2c26b3d44fc78dc2c1e8eda46400'
[info] Deluge key 'default_daemon' will have a new value 'b79a2c26b3d44fc78dc2c1e8eda46400'
[info] Writing changes to Deluge config file '/config/web.conf'...
2022-12-09 09:01:06,367 DEBG 'watchdog-script' stdout output:
[info] Deluge process started
[info] Waiting for Deluge process to start listening on port 58846...
2022-12-09 09:01:06,827 DEBG 'watchdog-script' stdout output:
[info] Deluge process listening on port 58846
2022-12-09 09:01:13,022 DEBG 'watchdog-script' stdout output:
Setting "random_port" to: False
Configuration value successfully updated.
2022-12-09 09:01:13,023 DEBG 'watchdog-script' stderr output:
<Deferred at 0x7f3d2e306140 current result: None>
2022-12-09 09:01:18,722 DEBG 'watchdog-script' stdout output:
Setting "listen_ports" to: (25922, 25922)
Configuration value successfully updated.
2022-12-09 09:01:18,722 DEBG 'watchdog-script' stderr output:
<Deferred at 0x7fb93d7be290 current result: None>
2022-12-09 09:01:24,783 DEBG 'watchdog-script' stderr output:
<Deferred at 0x7feeb44ba1a0 current result: None>
2022-12-09 09:01:24,919 DEBG 'watchdog-script' stdout output:
[info] No torrents with state 'Error' found
2022-12-09 09:04:18,423 DEBG 'watchdog-script' stderr output:
corrupted size vs. prev_size`

I have yet to try a different VPN (currently using Sweden) to see if that changes anything.

**Comment by tom472** [comment]
Have you tried a different VPN endpoint yet?
Did that help/make any difference?

I'm not seeing or able able to reproduce the issue.

**Comment by nickelnine** [comment]
Yes, I tried a different one but same result at the time (last night). I tried a few other things but nothing seemed to work.

Later last night, it all seemed to come back and operate normally again. I have no idea what the problem was; hope it never comes back.

**Comment by tom472** [comment]
OK - Thanks for the update.
