### ISSUE TITLE
Allow the user to select a specific PIA server.

### ISSUE THREAD

**Issue by Ryanb58** [tom472/mediabox#25]
I like to use a specific PIA server. It would be nice if the script let one select their favorite.

**Comment by tom472** [comment]
Do you know which server you are interested in?

Just an FYI - the Deluge VPN setup strongly recommends a server that allows port forwarding.

If I did add the ability to select a specific server I would most likely still leave the choice from the port forwarding servers list -- via PIA this is the list:

>Enable port forwarding in the application by entering the Advanced area, enabling port forwarding and selecting one of the following gateways:
>CA Toronto
>CA Montreal
>CA Vancouver
>Netherlands
>Sweden
>Switzerland
>France
>Germany
>Romania
>Israel

Does the server you prefer appear in this list?
If yes - then that is good and I will work on adding a user selection option for the VPN.
If the server you do not prefer is not here let me know and we might need to work something else out.

**Comment by Ryanb58** [comment]
The server I like to use is on that list. I think most people who to set this up will most likely use one at random or select one that they like best. I know the high level laws in the country I choose, so as to ensure my torrents are not illegal.

**Comment by tom472** [comment]
@Ryanb58 I have a working demo of VPN selection in a separate branch right now if you want to test it.

https://github.com/tom472/mediabox/tree/VPN_Menu

I have for the most part put it through its paces in testing and it appears to be good.
Expecting to merge this into master by the weekend hopefully.

If you try it - let me know if you have any issues.

Thanks
--Tom

**Comment by tom472** [comment]
@Ryanb58 This issue has been merged into master via https://github.com/tom472/mediabox/pull/28 
Please let me know if it works for you.

**Comment by tom472** [comment]
This has been tested and appears to be working correctly.

If anyone has any problems with using it please let me know.
