### ISSUE TITLE
deluge/sonarr integration

### ISSUE THREAD

**Issue by rudolph4404** [tom472/mediabox#33]
To use Sonarr with Deluge, Deluge's WebUI & Label Plug-ins have to be installed. But in order to do this, Deluge asks for the Plug-in .egg file. These .egg files are something to do with the version of python that is installed, http://mrtopf.de/en/a-small-introduction-to-python-eggs/, but this does not appear to be installed in the container.

**Comment by tom472** [comment]
I guess my first question would be - 
Are you actually using / wanting to use the "Label" plug-in?

If not - then when you are configuring Sonarr - just leave the box for category blank.
Then test the connection and it should succeed fine.

If you are really wanting to use the label plugin I can see if we can get that activated and remain in place through container stops and starts -- let me know.

**Comment by rudolph4404** [comment]
Sonarr wants a sonarrtv label so that it knows what to move to its permanent location. I haven't tried yet, but I'm guessing radarr will want a similar label for movies.Is there another way for the file management to work?If not, I'm stuck needing the labels.-ChuckOn Mar 11, 2018 9:14 AM, Tom Morgan <notifications@github.com> wrote:I guess my first question would be -
Are you actually using / wanting to use the "Label" plug-in?
If not - then when you are configuring Sonarr - just leave the box for category blank.
Then test the connection and it should succeed fine.
If you are really wanting to use the label plugin I can see if we can get that activated and remain in place through container stops and starts -- let me know.

**Comment by tom472** [comment]
Are you sure they're "needed"?
Couchpotato and Sickrage have no problems moving their content with out labels. 
Have you tried it yet to see what happens? Do the files get moved at all?
I'll try with a couple files to see what happens. I generally use CP and SR tho so I haven't messed with Sonarr and Radarr much yet.

**Comment by tom472** [comment]
@rudolph4404 - FYI - I'm still looking at this.
I think I might see what's happening.
I'm seeing errors with where Sonarr is looking for the completed files.
I'm checking into it.

**Comment by tom472** [comment]
@rudolph4404 -- Are you using Sonarr with Usenet or Torrent?

I added Sonarr to Mediabox because there were a bunch of requests for it, I've actually never used it before testing for this issue, gotta say I'm not that impressed.
I cannot figure out why anyone would use this over SickRage .. 

However - I think the root of the issue is that the container is configured to be looking at a folder called `/data/completed` for finished files - but yet the container settings page for this container say to map to `/downloads`.

I think there is a misconfiguration in the container itself - going to see if I can chase it down.

**Comment by rudolph4404** [comment]
I use sonarr with torrents. You are correct in that the labels are not mandatory, but they come in handy when there is related media (movies, books, comics, etc). Less chance of confusion over what app needs to decide on a final destination. The labels allow the sonarr family to know which app requested the download.

On March 13, 2018 11:14:20 PM CDT, Tom Morgan <notifications@github.com> wrote:
>@rudolph4404 -- Are you using Sonarr with Usenet or Torrent?
>
>I added Sonarr to Mediabox because there were a bunch of requests for
>it, I've actually never used it before testing for this issue, gotta
>say I'm not that impressed.
>I cannot figure out why anyone would use this over SickRage .. 
>
>However - I think the root of the issue is that the container is
>configured to be looking at a folder called `/data/completed` for
>finished files - but yet the container settings page for this container
>say to map to `/downloads`.
>
>I think there is a misconfiguration in the container itself - going to
>see if I can chase it down.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/tom472/mediabox/issues/33#issuecomment-372899245

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tom472** [comment]
So the deluge container is way to involved to re-create for me to add in the labels plugin.
binhex has done some serious magic with that container for all the VPN and PIA stuff to work together.

I can see if we might be able to add it after the fact but I'm not sure what I'll be able to do but I'll try a few things.

**Comment by tom472** [comment]
Just tested Deluge with the label plug-in activated via the WebUI and sent 2 files via Sonarr. It worked without issue, the activation of Deluge as the download client in Sonarr with a label in the "category" field tested OK.

Then the files sent to Deluge used the label fine.
This seems to be working as expected.
