### ISSUE TITLE
Unable to load deluge

### ISSUE THREAD

**Issue by nick-zanobini** [tom472/mediabox#34]
After installing and configuring everything the only thing I can't get to work is deluge. When I try and open it both from the home page and with the port specified it refuses to connect. Did I miss something?

This is awesome thank you.

**Comment by tom472** [comment]
The only thing I can think of could be this:
The Deluge container has a bunch of VPN firewall rules encoded in it.
You have to be on the same network subnet as the Deluge container to be able to access it's web interface.

When setting up other containers to "talk" to Deluge - did they work?
i.e. when testing the connection(s) from Sickrage or Couchpotato or Sonarr etc. - did the test connections work? This wil at least tell us if the container is up and functioning correctly.

**Comment by tom472** [comment]
@nick-zanobini Any updates / Any luck?

**Comment by nick-zanobini** [comment]
@tom472 Yes I installed it in my /opt folder which caused the VPN container to not start as well as it didn't finish copying the .conf file for PIA.

**Comment by tom472** [comment]
So is it working OK now?
Can we close this issue?

**Comment by nick-zanobini** [comment]
@tom472 I can load deluge now but the logs continually give this message: 

`2018-04-04 17:48:22,027 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 1 retries left
[info] Retrying in 10 secs...`

**Comment by tom472** [comment]
@nick-zanobini 
I have entries like that in my logs too.
They seem to go away if the deluge container is restarted, they also do not appear to affect the use of Deluge either.
They may be related to some of the tests that container does to verify that the VPN tunnel is up or if the external IP has changed.

Do those errors appear to be affecting your use of the Deluge container/the overall Mediabox stack?

**Comment by nick-zanobini** [comment]
@tom472 So it appears I am able to obtain an IP from PIA but I cant access the Deluge Web UI from my local network and when i try and test the connection between radarr and deluge it is unable to connect

**Comment by tom472** [comment]
When you click on the Deluge button on the Muximux landing page what happens?

Can you paste in your variables from the "Troubleshooting" section of the of the Mediabox page? (please strip your PIA creds and any other passwords)

Also Radarr ~I believe~ likes to use the "Label" feature by default when talking to Deluge - which is not "on" by default in Deluge - so if there is a box for "category" try leaving it blank.

**Comment by nick-zanobini** [comment]
So when testing in Radarr this is the error I get with those settings: Unknown exception: Cannot access a disposed object. Object name: 'System.Net.Sockets.NetworkStream'.

Slightly stripped `.env` variables:
```
LOCALUSER=admin
HOSTNAME=HomeServer
IP_ADDRESS=10.0.0.XX
PUID=1000
PGID=1000
PWD=/home/admin/mediabox
PIAUNAME=USERNAME
PIAPASS=PASSWORD
CIDR_ADDRESS=10.0.0.0/24
TZ=America/Los_Angeles
PMSTAG=public
PMSTOKEN=CLAIM
PORTAINERSTYLE=--no-auth
VPN_REMOTE=sweden.privateinternetaccess.com
CPDAEMONUN=admin
CPDAEMONPASS=password
NZBGETUN=admin
NZBGETPASS=password
```

When clicking on deluge in Muximux I get the following: IP_ADDRESS took too long to respond

**Comment by tom472** [comment]
At this point I'm wondering if you have bad images of the containers.
Can you try this:

`$ docker rm -f delugevpn`
`$ docker rm -f radarr`
`$ docker rmi -f binhex/arch-delugevpn`
`$ docker rmi -f linuxserver/radarr:latest`
`$ cd /home/admin/mediabox`
`$ docker-compose up -d`

After the new images download and the containers spin up, try going to Deluge from the Muximux page and see if you are able to access it.

**Comment by tom472** [comment]
@rudolph4404 thanks for that info...
Guess I'll try to throw 17.10 on my test VPS and see what happens.

@nick-zanobini are you running 17.10 or 16.04?

**Comment by rudolph4404** [comment]
18.04 will be released later this month. -ChuckOn Apr 5, 2018 9:07 PM, Tom Morgan <notifications@github.com> wrote:@rudolph4404 thanks for that info...
Guess I'll try to throw 17.10 on my test VPS and see what happens.
@nick-zanobini are you running 17.10 or 16.04?

**Comment by tom472** [comment]
@rudolph4404 Great.. I like to target the LTS releases, looks like I'll be waiting until the end of April and start testing with 18.04

**Comment by nick-zanobini** [comment]
@tom472  I am running Ubuntu Server 16.04 LTS. Deleting the container images solved the problem thank you!

**Comment by enoch85** [comment]
I have the same issue on Ubuntu 18.04.1. A clean install for the sole purpose of installing Mediabox, following the exact instructions and also tried `rmi` like described here.

Still same error: timeout.

Do I need to open any ports in my firewall? I tried opening port 1198 (PIA) and did a allow * for the LAN IP but it didn't help.

Please advice!

**Comment by tom472** [comment]
OK this has been closed for a bit so let me check some details:

When you say: 

> Still same error: timeout.

This is when trying to load Deluge from the Muximux interface?
And you are trying to access it from a PC that is on the same LAN as the Mediabox PC correct?

Are you able to hit the Deluge via it's direct address? `http://mediaboxip:8112`

Does Portainer say the container is up?

Anything in the logs for the Deluge container? (Via Protainer)

Is the `CIDR_ADDRESS=` variable correct for your network? 
(i.e. it includes the IP of the device you are trying to access Deluge from?)

**Comment by enoch85** [comment]
@tom472 Sorry, it turned out to be that I needed to add my laptops IP in the config. You can close this.

**Comment by tom472** [comment]
Just curious .. You added it to which "config".

**Comment by enoch85** [comment]
Here you go: https://github.com/binhex/arch-rtorrentvpn/issues/84#issuecomment-450655052

I ended up using that instead. Sorry for taking your time.

**Comment by tom472** [comment]
@enoch85 Gotcha - so you added in a second CIDR to the Deluge config so that more than one local LAN segment has access to Deluge based on the IPTables rules.

Glad you got it worked out.

**Comment by wiinc1** [comment]
I seem to have a similar issue as many of the users in this issue thread except the steps suggested didn't work.

I'm running Ubuntu 16.04.6 LTS.

I deleted the containers and rebuilt them - didn't resolve the issue.

I have attempted to hit the app via all the ports associated with the app shown in Portainer.  Those ports are:  58846, 58946, 8112, 8118.

I have attempted to access Deluge via the MuxiMuxi homepage for all the apps.

Portainer shows the container as "running"

In the logs access via Portainer I see something similar to one of the other users.  Below is a snippet of the logs:

```
2019-06-15 18:18:22,029 DEBG 'start-script' stdout output:
[warn] PIA endpoint 'nl.privateinternetaccess.com' is not in the list of endpoints that support port forwarding, DL/UL speeds maybe slow
[info] Please consider switching to one of the endpoints shown below
2019-06-15 18:18:22,029 DEBG 'start-script' stdout output:
[info] List of PIA endpoints that support port forwarding:-
[info] ca-toronto.privateinternetaccess.com
[info] ca-montreal.privateinternetaccess.com
[info] ca-vancouver.privateinternetaccess.com
[info] de-berlin.privateinternetaccess.com
[info] de-frankfurt.privateinternetaccess.com
[info] sweden.privateinternetaccess.com
[info] swiss.privateinternetaccess.com
[info] france.privateinternetaccess.com
[info] czech.privateinternetaccess.com
[info] spain.privateinternetaccess.com
2019-06-15 18:18:22,029 DEBG 'start-script' stdout output:
[info] ro.privateinternetaccess.com
[info] israel.privateinternetaccess.com
2019-06-15 18:18:22,043 DEBG 'start-script' stdout output:
[info] Attempting to curl http://209.222.18.222:2000/?client_id=e2bcb73116a606e59e963f97f1a0fd410f64bf79c6739fc869b4ace86ce219ae...
2019-06-15 18:18:22,150 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 12 retries left
[info] Retrying in 10 secs...
2019-06-15 18:18:32,271 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 11 retries left
[info] Retrying in 10 secs...
2019-06-15 18:18:42,399 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 10 retries left
2019-06-15 18:18:42,400 DEBG 'start-script' stdout output:
[info] Retrying in 10 secs...
2019-06-15 18:18:52,531 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 9 retries left
2019-06-15 18:18:52,531 DEBG 'start-script' stdout output:
[info] Retrying in 10 secs...
2019-06-15 18:19:02,655 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
2019-06-15 18:19:02,655 DEBG 'start-script' stdout output:
[info] 8 retries left
[info] Retrying in 10 secs..
2019-06-15 18:19:12,783 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 7 retries left
[info] Retrying in 10 secs...
2019-06-15 18:19:22,912 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 6 retries left
[info] Retrying in 10 secs...
2019-06-15 18:19:33,039 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 5 retries left
[info] Retrying in 10 secs...
2019-06-15 18:19:43,169 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 4 retries left
[info] Retrying in 10 secs...
```

What have I done wrong ;)  ?
