### ISSUE TITLE
Define media volume on init

### ISSUE THREAD

**Issue by jthegedus** [tom472/mediabox#35]
as discussed here - https://github.com/tom472/mediabox/issues/30, most users will be using a different volume for their media than the host drive of the containers. It would be good if you could set a volume on init for all "finished" media to be moved to and then metadata services could run on that data. Or even more simply, advise everyone to "use drive pooling or raid first" and run this on the single volume.

**Comment by tom472** [comment]
Just dropping back in - 
Work has been a little nuts - but I do hope to be working on this and the update feature this weekend.

**Comment by tom472** [comment]
Just another heads-up,
The upgrade part has been pushed to master - the set your existing media location part should hopefully be pushed very soon.

**Comment by jthegedus** [comment]
@tom472 I appreciate the updates :100:

**Comment by tom472** [comment]
OK this request is finally live, sorry for such a long delay on it.
If you have the version of Mediabox that can auto-update itself you should be able to just re-run `./mediabox.sh` to pull the latest version that has this in it.

Let me know if there are any issues etc.

Thanks

**Comment by jthegedus** [comment]
@tom472 Awesome! I'll give this a go! Any problems will be raised as new issues :100:
