### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by llDunno** [tom472/mediabox#36]
Just installed mediabox using the instructions provided. All the containers I can see in portainer but I can't go to my local ip. If I go to my local ip or http://docker it can't connect or says 502 bad gateway.

**Comment by tom472** [comment]
How did/do you see them in Portainer?
Did you go to Portainer's interface directly?
So the Muximux landing page doesn't load?

From the Portainer interface >> Container List 
The "Published Ports" column links are "clickable" -- are you able to click on any of those links and get to the interfaces of the containers?

And to verify - once the set-up was complete if you go to:
http://your.server.ip.address
You are not getting the Muximux landing page to load?

**Comment by llDunno** [comment]
Muximux**

**Comment by tom472** [comment]
Try using Portainer to stop and then remove the Muximux container.
Then use Portainer to delete the muximux image.
Go back to the mediabox folder and run: docker-compose up -d
This should re-pull the muximux image and start it up again.
Maybe it was a bad image download.

**Comment by llDunno** [comment]
I realize it's probably because I've got openvpn running on port 80.... I'll close this issue for now.
