### ISSUE TITLE
Tool for .sh scripting

### ISSUE THREAD

**Issue by jthegedus** [tom472/mediabox#38]
@tom472 Just a suggestion, but I've found https://github.com/koalaman/shellcheck extremely helpful for doing any `.sh` work. Highly recommend :+1: 

_just thought I would share this if you didn't know about it._

**Comment by tom472** [comment]
Thanks - Yes - I've seen that and used it from time to time.

I am thinking of starting to add version numbers to Mediabox.
If I start to do that I am also going to start running the code through code checkers/cleaners.

The first goal was to get something that works - now that I have pretty much made it to that point, it's time to make it better.

Thanks again for the suggestion.

**Comment by jthegedus** [comment]
This sounds great, thanks for your work! :slightly_smiling_face:
