### ISSUE TITLE
Changed no-auth flag inside of portainer for portainer, can't connect now

### ISSUE THREAD

**Issue by jordanyeo** [tom472/mediabox#43]
I originally installed portainer with the no-auth flag, but want to lock it down with authentication. I edited the portainer container in portainer to remove that flag, and now I'm getting connection refused. How can I either set that flag back, or make the auth work? I did a bunch of changes to my docker environment within portainer, so my docker compose file is out of date. Thanks!

**Comment by tom472** [comment]
Yeah you have to be careful changing Portainer "in" Portainer it kind of stomps on itself.

Here are two ways to fix this:

If you cloned Mediabox before auto-updating was added you should look a the "Upgrading Mediabox" section in the readme, follow those steps and update Mediabox.
If you cloned it after Auto-Update was added you can re-run `./mediabox.sh` to be re-asked the Portainer style you would like to use.

The quick and dirty method would be:
`$ docker stop Portainer`
`$ nano path/to/mediabox/.env`
In the .env file make sure the `PORTAINERSTYLE` variable reads as `PORTAINERSTYLE=`
Then `$ cd /path/to/mediabox`
And `$ docker-compose up -d`

That will stop the Portainer container (so changes can be made)
Then you're editing the `.env` file which feeds variables to the `docker-compose.yml` file
And turning off the "No-Auth" command to Portainer which will then default Password access.
Then starting the stack back up.

Let me know how it goes.

**Comment by tom472** [comment]
I'm going to guess that no news is good news and that this is resolved.
If that is not the case and there is still an issue with this, please re-open the issue.
