### ISSUE TITLE
Stop uhttpd in installation script

### ISSUE THREAD

**Issue by trevor-e** [tom472/mediabox#47]
I'm upgrading for the first time in a while, back from when you used `uhttpd` to serve the welcome page. The installation script doesn't account for that when stopping existing docker containers, and then fails to launch `Muximux` because port 80 is already in use. 

This cascades into other problems such as infinitely waiting on:

```
Configuring DelugeVPN and NZBGet - Muximux files - Permissions 
This may take a few minutes...
```

because `Muximux` was not launched properly.

Running `docker stop uhttpd` before the installation script fixes the issue.

**Comment by tom472** [comment]
OK thanks for catching that, I can build in a fix for this.
Totally forgot that was in there way back.

Should be able to get this corrected pretty quickly.

**Comment by tom472** [comment]
Change made to the `mediabox.sh` script to account for the old uhttpd container that used to provide the Welcome page.

Big thanks @trevor-e for the reminder that container used to be there.
And thanks for coming back to the project for an update after a while.

How is Mediabox doing now - Is it (hopefully) improving / getting better / more useful?

**Comment by trevor-e** [comment]
Awesome work, that was fast, thanks!

Overall it's working great for my needs, though I'm really only using Plex/Deluge at the moment. Been meaning to play around with Sonarr/Radarr, so it's nice that they are already integrated with everything for when I'm ready. The Muxumux dashboard is a nice improvement over the old page. Everything is definitely trending up, thanks for all the updates.

The only hurdle was integrating my NFS drive to store the media, but it wasn't that hard to get something working. My current setup is an Intel NUC with a small SSD that's hooked up to a 3TB network drive. I tried a few different ideas, such as creating symbolic links with the default mediabox content directories to my NFS in order to keep the default project `docker-compose.yml`. Gave up after a while since I don't know enough about NFS.

**Comment by tom472** [comment]
As long as the media directories are addressable via a file path that will stay consistent, mediabox will now ask you where those paths are and then adjust the paths the the project accordingly.
Paths needed are:
TV
Movies
(music coming soon)

**Comment by rudolph4404** [comment]
How about paths for books & comics?-ChuckOn Jun 23, 2018 9:03 AM, Tom Morgan <notifications@github.com> wrote:As long as the media directories are addressable via a file path that will stay consistent, mediabox will now ask you where those paths are and then adjust the paths the the project accordingly.
Paths needed are:
TV
Movies
(music coming soon)

**Comment by tom472** [comment]
@rudolph4404 Now that the project has a state where I consider it fully working I will be adding in more apps.
I still have the ones you mentioned in the older issue on the list. New apps will be coming soon and then yes new paths will be requested too.
