### ISSUE TITLE
Way to not install/uninstall/disable programs not being used

### ISSUE THREAD

**Issue by WoosterInitiative** [tom472/mediabox#49]
I use Sonarr/Radarr, would like to be able to free up resources by not having Sickbeard and CouchPotato installed. Also, minio, etc.

**Comment by tom472** [comment]
What resources are you looking to free up?

All you need to do is go into Portainer and stop any of the containers that you do not want/use and they will stop. And as long as they are "stopped" properly even with reboots etc. they will remain in a stopped state.

After that the only "resource" being used up those containers would be like 500MB of storage space.

Do you need something more than that?

I previously looked at coding a walk-through of do you want this container or do you want that container ...
But it ends up adding way to much code for the now 16 containers that Mediabox is running by the time it is up and running that it just doesn't seem worthwhile when Portainer can be used to stop and unused containers.

**Comment by tom472** [comment]
@WoosterInitiative Was this suggestion helpful enough for you?
Do you have additional questions?

**Comment by WoosterInitiative** [comment]
It is helpful... As a learning experience I'm going to play with a fork,
but I think I've got what I need! Thanks!

**Comment by tom472** [comment]
OK sounds good.
