### ISSUE TITLE
Add your affiliate link to your PIA link in README

### ISSUE THREAD

**Issue by stvhwrd** [tom472/mediabox#5]
Add your affiliate link to your PIA link in README.  You deserve to benefit from whatever new signups they get as a result of this project you're developing.

See https://www.privateinternetaccess.com/pages/affiliates/ for information on their generous affiliate program.

**Comment by tom472** [comment]
Thanks for the tip - hadn't really thought of that.
I'll try to get that added in.

**Comment by tom472** [comment]
I think I might pass on this.
Thanks for mentioning it and passing it on but not really sure I want to create an affiliate account.
