### ISSUE TITLE
First install

### ISSUE THREAD

**Issue by cthog** [tom472/mediabox#51]
I try logging into my host ip, as instructed, and I get "nginx 502 bad gateway", so I can't complete setup.  Any idea what this is?

Edit: ended up reinstalling Ubuntu Server, but my theory is that I had installed from root account.

**Comment by tom472** [comment]
Correct - there is no part of "Mediabox itself" that should be done as root.

Only the set-up steps for the installation of the prerequisites etc.

The rest of the Mediabox setup actually depends on knowing who you (the current user) are and sets variables based on that.

So are you working OK now?

**Comment by cthog** [comment]
Yes, thank you.  Although I have a separate issue that I'll start a new thread on.

**Comment by tom472** [comment]
OK - Sounds good I'll check the other thread.
