### ISSUE TITLE
ERROR: write /var/lib/docker/tmp/GetImageBlob684890137: no space left on device

### ISSUE THREAD

**Issue by element465** [tom472/mediabox#57]
Trying to install the script again for a fresh install on Ubuntu Server 18.04, and when it gets to the pulling of the dockers, it downloads and then I get this error: 

`ERROR: write /var/lib/docker/tmp/GetImageBlob684890137: no space left on device`

Please see image: http://prntscr.com/kkdpe6

The user has been added to the docker group, and the instructions have been followed. 

Is there something that I am missing?

**Comment by tom472** [comment]
What is the size of the disk you are installing on?

Also - let's try a docker cleanup:
Can you run `docker system prune` and select "y" for the answer?

Then try it again.

**Comment by element465** [comment]
Tried the docker clean up - it cleaned up 0 bytes.

Dish is 320gb, and a fd -h shows: http://prntscr.com/kkkhn7

Could it perhaps be a permissions error? I have followed the instructions to the letter, and it was on a fresh install.

I'll try a fresh install tonight again of Linux, does it work better on 16.04 or 18.04? I was using a fresh 18.04 fresh.

**Comment by tom472** [comment]
It should be fine on both 16.04 and 18.04.

Do any containers work?

Can you try running this:
`docker run -d -p 80:80 ksdn117/test-page`

This should download a small nginx container and serve up a "Container is Running" (image) page at: `http://127.0.0.1`

**Comment by element465** [comment]
```
Unable to find image 'ksdn117/test-page:latest' locally
latest: Pulling from ksdn117/test-page
df22f9f3e4ec: Extracting  51.36MB/51.36MB
a3ed95caeb02: Download complete
9f0a434912c7: Download complete
7c5f5e214e04: Download complete
4b6596bcdcf9: Download complete
ec33f9a4eab3: Download complete
0f62e9386b58: Download complete
99730ebeaded: Download complete
658147fee531: Download complete
d27365680269: Download complete
8e87ad1fc3ba: Download complete
docker: failed to register layer: Error processing tar file(exit status 1): write /usr/share/zoneinfo/right/Asia/Choibalsan: no space left on device.
```

I am installing the script to my home/user folder and set the media in the options to an exeternal mounted drive (which it can read and write to as it has created the 'download' folder to).

**Comment by tom472** [comment]
Something seems not right with your Docker set-up.
That is a dead simple nginx container that just shows a single image page when complete.

If that is not working, and throwing the same error, there seems to be an issue with the Docker install itself.

What is the output of: `docker version`

**Comment by element465** [comment]
Seems to be a once off glitch - I reinstalled everything from scratch, and did the exact same thing (followed the instructions perfectly) and it worked without a hitch.

The only thing I did different was install the OS without LVM this time.

Thanks Tom for trying to help, it seems to just be a once off issue and a complete reinstall fixed it. :-)

**Comment by tom472** [comment]
@element465 That's awesome! Glad to hear it was just a one-time thing.

Stop on back with any other issues/questions ..

And Enjoy Mediabox!
