### ISSUE TITLE
Radarr and Sonarr - Folder is not writable by user abc

### ISSUE THREAD

**Issue by element465** [tom472/mediabox#58]
Trying to choose the select path folder as can be seen in below screenshot, but when I go to add the /movies or /tv, I get the error `Folder is not writable by user abc`. This happens in both Radarr and Sonarr for each of their folders.

http://prntscr.com/kksim7

/data/competed does not have this error (but it should be going there).

Any suggestions? Have I done something incorrect? Not sure how to give user abc permissions for the folder either.

**Comment by element465** [comment]
Seems to be because the folders were created by the script but as user root?

**Comment by tom472** [comment]
You didn't run the script with `sudo` did you?
(Just FYI it should not be run with sudo)
The script should be run as you so that all folders etc. get created by/as you.

You are using you're own locations for the content folders right?

**Comment by element465** [comment]
Maybe I did by accident? Not sure.

A complete reset fixed it, not sure why it happened.
