### ISSUE TITLE
Multiple drives Issue

### ISSUE THREAD

**Issue by erfly7** [tom472/mediabox#60]
Took a  look at this while ago and looked like good choice but no VPN, now has PIA VPN so that is perfect, question does the VPN cover all the apps deluge, nzbget?

and the second issue which could never figure out if mediabox and ubuntu are installed on a smallish SSD but all my files are on 4 bigger HDD how to you set them up?

**Comment by tom472** [comment]
The VPN covers deluge, there really isn't a need for it anywhere else. Use SSL with Usenet if you go that route.

For the second question yes you can point to directories that are not on the same disk as Mediabox.
During the setup script you are asked for the paths to your TV, movies, music, etc folders.
Then those locations are used during the setup.

**Comment by tom472** [comment]
@erfly7 Did this help answer your questions?

I'm on vacation this week so my access to check-in on things is spotty.
Just wondering if you have tested this again yet?

Thanks
--Tom
