### ISSUE TITLE
nzbget mounted volume issue

### ISSUE THREAD

**Issue by jthegedus** [tom472/mediabox#61]
This may be user error...

I ran the setup script with this output:

<details>
<summary>img: setup output</summary>

![mediabox--setup-script](https://user-images.githubusercontent.com/20798510/45133230-75f6e580-b1d7-11e8-823f-bfba983ee13c.png)
</details>
</br>

As you can see, my specified volume does not match that used by the NZBGet container:

setup:
`media/zd/data/downloads`
container:
`media/zd/data/downloads/completed`

<details>
<summary>img: nzbget container volumes</summary>

![nzbget-volumes](https://user-images.githubusercontent.com/20798510/45133231-78f1d600-b1d7-11e8-8331-084fcb2aba8c.png)

</details>
</br>

This causes issues when Sonaar tries to retrieve files from 
`/media/zd/data/downloads/completed` but they are actually located at `/media/zd/data/downloads/completed/completed`

this is the folder structure I end up with for nzbget:

```
data/
    downloads/
        completed/
            intermediate/
            nzb/
            nzbget.log
            queue/
            tmp/
            completed/
                Movies/
                Series/
        incomplete/
```

**Comment by tom472** [comment]
OK I'll have to look at this when I get a minute. I'm on vacation right now and don't have the ability to do much testing. 

Thanks for the report I'll see what I can find out.

**Comment by jthegedus** [comment]
Cheers, I fixed the issue with Portainer, so only affects people relying on the automated setup.

`ifconfig` relies on `net-tools` which is not listed as a pre-req. `sudo apt install net-tools -y` solves that.

I'm using Ubuntu 18.04 LTS

It seems that Sonaar and Radaar also require a `downloads/` binding to the DOWNLOADS directory.

If I find the time over the next week to contribute and test these I'll give it a go

**Comment by tom472** [comment]
Yes I love to see what you did in Portainer to fix it so I can fix it in the script. 

And I knew ifconfig was going away in favor of ip .. so I'll have to work on getting the script to work with that command instead. 
Or I'll have to add net- tools to the pre-reqs, but I'd like to try and fix it with out needing the additional package.

Thanks

**Comment by tom472** [comment]
@jthegedus Any chance you can stop back and post the change you made in Portainer?

So that I can add it in to be fixed

Thanks
--Tom

**Comment by jthegedus** [comment]
Yep, no problem! Sorry, will do so now :+1:

**Comment by jthegedus** [comment]
@tom472 Here are the changes:

nzbget:
To fix the aforementioned nzbget nesting issues, **replace** the volumes with this
```yaml
  volumes:
    - '${DLDIR}:/downloads'
```

radarr & sonarr:
Add this in **addition** to the existing volumes
```yaml
  volumes:
    - '${DLDIR}:/downloads'
```

**Comment by tom472** [comment]
@jthegedus Excellent - thanks for the info.

I'll take a look a this and hopefully get it added in tonight.

Thanks
--Tom

**Comment by jthegedus** [comment]
No problemo. Sorry it wasn't a pr, I didn't have the time to sufficiently
prepare and test one this evening. Thanks for all your work!

On 17 Sep. 2018 10:47 pm, "Tom Morgan" <notifications@github.com> wrote:

@jthegedus <https://github.com/jthegedus> Excellent - thanks for the info.

I'll take a look a this and hopefully get it added in tonight.

Thanks
--Tom

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tom472/mediabox/issues/61#issuecomment-422001126>, or mute
the thread

**Comment by tom472** [comment]
@jthegedus No worries about it not being a PR - its pretty minor changes.
Thanks again for letting me know about the issue and providing a fix for it.

Much appreciated!

**Comment by tom472** [comment]
This didn't work - after updating my local instance, docker-compose up threw some errors.
Gonna have to roll it back and test some more.

**Comment by tom472** [comment]
Still having some issues here.
Probably b/c I don't use NZBGet so I don't "really" get to see how the layout looks.
But I think I'm pretty close.

Hang in ...

**Comment by jthegedus** [comment]
Here's some more info

my working nzbget volumes:

![nzbget-volumes](https://user-images.githubusercontent.com/20798510/45729717-1950ed00-bc11-11e8-9d49-e964f55c703c.png)

my dirs defined during setup:

![mediabox-dirs](https://user-images.githubusercontent.com/20798510/45729719-19e98380-bc11-11e8-8008-6f12235b0a95.png)

Maybe it depends on the version of the nzbget container from dockerhub?

**Comment by tom472** [comment]
Excellent thanks for the additional info that will help. 
I'll try and get back to this tomorrow.

**Comment by tom472** [comment]
Just jumping back in to say I hope to get to this soon.
Sorry for the delay - been a little busy lately.

**Comment by tom472** [comment]
Finally fixed this - no idea why I never came back to it.
Should be fixed now via commit: https://github.com/tom472/mediabox/commit/42bb7d3e18b2e7508aff4e25ae0482d5201be8d1

**Comment by jthegedus** [comment]
I'll give it a go next week and report back, thanks :smile:
