### ISSUE TITLE
Portainer not loading in Muximux

### ISSUE THREAD

**Issue by tom472** [tom472/mediabox#63]
There was an update to Portainer and it looks like it is no longer able to load in a frame.
So this is making it not load in Muximux.
Current workaround is to open Portainer at its full URL: http://yourmediaboxip:9000

I have noticed this as a trend and will probably need to look at other options to replace Muximux.

Organizr has been mentioned and tested before but it has not way to be "automatically" configured as it holds all its settings in a sqlite db.

If anyone has suggestions or ideas please let me know.

Thanks
--Tom

**Comment by rudolph4404** [comment]
There is a command line interface to the sqlite database. The command is sqlite3. You give it the pathname to the database file and a SQL statement. SELECT to query records. INSERT to create a new record. UPDATE to change records. DELETE to remove records. You just need to know the structure of the Organizr database.-ChuckOn Sep 18, 2018 10:35 PM, Tom Morgan <notifications@github.com> wrote:There was an update to Portainer and it looks like it is no longer able to load in a frame.
So this is making it not load in Muximux.
Current workaround is to open Portainer at its full URL: http://yourmediaboxip:9000
I have noticed this as a trend and will probably need to look at other options to replace Muximux.
Organizr has been mentioned and tested before but it has not way to be "automatically" configured as it holds all its settings in a sqlite db.
If anyone has suggestions or ideas please let me know.
Thanks
--Tom

**Comment by tom472** [comment]
Over on the Portainer project it looks like they are going to remove the headers config that is causing this issue. They then might be adding an option to enable/disable this setting later on.
(See https://github.com/portainer/portainer/issues/2279#issuecomment-425696691)

I'll leave this issue open here until I see the removal has been pushed to the main Portainer branch and is working again in Muximux.

**Comment by tom472** [comment]
The fix has been made upstream in Portainer.
Portainer now loads again via the Muximux interface.
