### ISSUE TITLE
snap docker

### ISSUE THREAD

**Issue by doughecka** [tom472/mediabox#64]
If Docker is chosen during Ubuntu install (at least on 18.04), it installs 'snap docker', which does not show up under normal apt-get commands when removing. Recommend making this change on the instructions:
Uninstall old versions: 
$ sudo apt remove docker docker-engine docker.io 
$ sudo snap remove docker 
It’s OK if apt or snap reports that none of these packages are installed.

**Comment by tom472** [comment]
Thanks that's good to know.
I'll add that to the README directions.

**Comment by tom472** [comment]
Sorry this took so long for just a minor change to the README I have been a little busy.

@doughecka thanks again for pointing this out and it has now been added to the README.
(via commit: https://github.com/tom472/mediabox/commit/fe47bd8ba675d43b46341d74714fdcd1c4df4493)
