### ISSUE TITLE
Muximux not loading on new build

### ISSUE THREAD

**Issue by nfields03** [tom472/mediabox#66]
I started up a fresh install from scratch of mediabox on my home server and everything seems to be coming up okay except muximux.  When I look in the Portainer logs for that container, I'm seeing the following error repeated over and over.  Maybe a slight adjustment in the config for it is required?  If it's a muximux build issue, i'm happy to close it out and take it up with them...

Thoughts?

[02-Jan-2019 16:49:37] ERROR: [pool www] please specify user and group other than root,
[02-Jan-2019 16:49:52] ERROR: [pool www] please specify user and group other than root,
[02-Jan-2019 16:53:02] ERROR: FPM initialization failed,
[02-Jan-2019 16:53:00] ERROR: [pool www] please specify user and group other than root

**Comment by tom472** [comment]
What user is running your containers?

What are the:
`PUID`
and
`PGID`
values in your `/mediabox/.env` file?

**Comment by nfields03** [comment]
It's brand new as of a few days ago, and I checked the file just now.  Both values are 0 in the .env file.

**Comment by nfields03** [comment]
Any particular concerns if I change it from 0/root to something else?

**Comment by nfields03** [comment]
Nevermind, I tried resetting the values in the .env file and then re-ran the mediabox.sh file, but the script overwrote my changes and put it back to 0/root.

**Comment by tom472** [comment]
You should not be running the script as root or with `sudo` .. you should be running it from a regular user account.

**Comment by nfields03** [comment]
Ahh, good to get clarified, thank you and testing it today.

**Comment by nfields03** [comment]
Looks like it worked, I will stand corrected and be sure to follow the readme to the **exact letter** in the future.  Thanks!

**Comment by tom472** [comment]
@nfields03 No problem - And you are not the first person to do that.

After `sudo` is used to do the installs, pre-reqs - the rest of the set-up is done using your regular account.
