### ISSUE TITLE
Failure connecting to Jacket indexers

### ISSUE THREAD

**Issue by rudolph4404** [tom472/mediabox#70]
Is this problem being tracked?
https://github.com/Sonarr/Sonarr/issues/2802
I appear to be having this problem.

**Comment by tom472** [comment]
Thanks for letting me know and referencing the linked issue.
I'll keep my eye on it and see what the solution(s) is/are.

**Comment by stannynuytkens** [comment]
Having the same issue:

Version 2.0.0.5301
Mono Version 5.8.0.108
Jackett Version 0.10.890.0

Jackett works fine on it's own and together with CP.

**Comment by tom472** [comment]
Closing this as the upstream issue is still open.

As soon as they have it fixed it should replicate into Mediabox.

Workaround of restarting the container(s) is available for now.
