### ISSUE TITLE
fresh install on fresh install of ubuntu

### ISSUE THREAD

**Issue by tbarrettjr93** [tom472/mediabox#71]
hi! i have recently freshly installed ubuntu 18.04 and tried to setup mediabox to run. i ran ./mediabox.sh and followed all the steps flawlessly. I get to the part where it says

 "Configuring DelugeVPN, NZBGet, Muximux, and Permissions 
This may take a few minutes..."

and it just sits here for ever. I've waited over an hour for this to get through and i dont know if its supposed to take this long but im assuming not. Please help.

**Comment by tbarrettjr93** [comment]
rebooted one more time and ran it again and now its all good!! this is awesome! thank you!

**Comment by tom472** [comment]
@tbarrettjr93 Thanks for letting me know you had a long delay at that section.

I will re-verify the command(s) at that point and make sure it is still correct.

Glad it worked for you after a reboot - and thanks for playing with Mediabox.

**Comment by bdmorin** [comment]
This happened to me too
```
0  1000  1872  1871  20   0  21608  5200 wait   Ss   pts/0      0:00          \_ -bash
0  1000  6932  1872  20   0  11592  3260 wait   S+   pts/0      0:00          |   \_ /bin/bash ./mediabox.sh
0  1000 16979  6932  20   0   6176   788 hrtime S+   pts/0      0:00          |       \_ sleep 1
```
I tried killing the sleep process, but no luck.

is mediabox.sh supposed to be run as root? The user I'm running it as has docker permissions.

**Comment by tom472** [comment]
No it should be run as you the user.
Are you sure your PIA credentials are correct?
Did you let the script create your content folder or did you set it?
If you set it, does the user have the right permissions to that folder?

**Comment by bdmorin** [comment]
Hmm.. Not entirely sure what I did wrong the first time, however I stopped everything with `docker stop $(docker ps -a -q)` then `docker system prune -a` then I saw some stuff wasn't owned by my user, but systemctl user. So I `chmod -R $USER:$USER ~/mediabox` then for good measure `chmod -R $USER:$USER /media` then ran the `./mediabox.sh` installer again, as my user account. And boom, everything came up. 

This is really a work of art man, thanks for your time and effort.

**Comment by tom472** [comment]
Hmm .. while I'm glad it's working for you this is kinda of the second report of stuff being owned by system ctl.
Can you by any chance recall what things had the wrong owner?

Thanks for playing with it and for the kind words.

**Comment by bdmorin** [comment]
I don't have my scrollback buffer, sorry. I know it was systemd and it was pretty much all the app directories in ~/mediabox, so stuff like `ombi`, `minio` and whatever had a different user. Which tells me I probably `sudo`'d something I shouldn't have.

**Comment by tom472** [comment]
OK no problem thanks so much for all the info.
Yes .. everything -after- installing the pre-reqs is done as your user, but it seems many people tend to run the script with sudo or as root.
I'm going to be putting in a check for that this weekend. 

Thanks again.
--Tom
