### ISSUE TITLE
Restoring Backups

### ISSUE THREAD

**Issue by wibuf** [tom472/mediabox#74]
Is there anyway we can add to the readme a quick guide on how to restore plex/radarr/sonarr backups? That will help a lot of people I think. 

Thanks

**Comment by tom472** [comment]
Hey @wibuf -- What types of backups are you referring to?

Backups from within the applications themselves?
Or
Backups from the included Duplicati application?

While there are some settings that need changing for use with Mediabox, Mediabox's documentation is not meant to replace the "general" documentation for each of the individual apps included. 
Adding documentation related to specific application tasks directly into Mediabox itself could lead to that information possibly becoming stale, incorrect, incomplete etc. should the application itself update their steps/process. 
 
Many of the applications included have their own excellent set(s) of documentation.
i.e. 
This is what I see for [Backup and Restore Sonarr](https://github.com/Sonarr/Sonarr/wiki/Backup-and-Restore)   

Does that help / make sense?

Thanks
--Tom

**Comment by tom472** [comment]
@wibuf -- Did the above info help?
Do you have anything additional to ask / add?

**Comment by wibuf** [comment]
No, I am good now thank you a bunch. One idea I had(this is probably the wrong spot for this), but would be to add in KVM/Kimchi. This would make mediabox more similar to Unraid but would still have more freedom having the individual dockers.

https://github.com/kimchi-project/kimchi

**Comment by tom472** [comment]
OK thanks for stopping back -- 

Kimchi looks pretty interesting, I'll put in on my radar and look into it.

Thanks
--Tom
