### ISSUE TITLE
Add SABnzbd support

### ISSUE THREAD

**Issue by wibuf** [tom472/mediabox#75]
Is it possible to add SABnzbd support?

**Comment by tom472** [comment]
This should be pretty easy to add.

The fine folks over at LinuxServer.io do have a Docker Image for SABnzbd so rolling that into Mediabox would likely be fairly easy to accomplish.

Stay tuned I'll try and get to this maybe this week.

Thanks
--Tom

**Comment by tom472** [comment]
So there is a bit of bad news - 
I can get the container added and working OK but it has an issue launching from behind Muximux. Looks like the SABnzbd container is doing some redirects immediately upon access which can be an issue for Muximux to handle.

Not giving up but not as simple of an add as I was expecting.

**Comment by tom472** [comment]
Is this still wanted/needed?
Or does NZBGet and/or NZBHydra2 cover the functionality?

**Comment by Bramblefoot** [comment]
It's probably a personal preference, but I've read that nzbget is lighter
weight and faster, which is preferred.

Just my 2 cents...

Bill

"Try not. Do, or do not. There is no try." - Yoda
