### ISSUE TITLE
sonnar & radarr not talking to deluge

### ISSUE THREAD

**Issue by rudolph4404** [tom472/mediabox#76]
sonarr & radarr have stop communicating with deluge.
No new downloads can be started.
No finished downloads can be imported.
If I test the connection from inside sonarr I get:
Unknown exception: The operation has timed out.: 'http://192.168.0.165:8112/json'
radarr reports the following:
Unknown exception: The operation has timed out.

I recently installed SSH tools on my system using these instructions:
https://www.cyberciti.biz/faq/ubuntu-linux-install-openssh-server/
I'm on Ubuntu 18.04. Upgraded from 16.04.

I did try rerunning mediabox.sh to see if that would clear things up - no luck.

**Comment by tom472** [comment]
@rudolph4404 - Are you sure the Deluge container is fully up and running correctly?
i.e. Can anything connect to Deluge?

I just went into my currently running config and Sonarr and Radarr are connecting fine using the "Test" function under Download Clients.

I'll test them both shortly on a freshly started stack and see how they are with that too.

**Comment by rudolph4404** [comment]
Deluge is up. I can manually add torrents.-ChuckOn Jun 2, 2019 11:39 AM, Tom Morgan <notifications@github.com> wrote:@rudolph4404 - Are you sure the Deluge container is fully up and running correctly?
i.e. Can anything connect to Deluge?
I just went into my currently running config and Sonarr and Radarr are connecting fine using the "Test" function under Download Clients.
I'll test them both shortly on a freshly started stack and see how they are with that too.

**Comment by rudolph4404** [comment]
Also, nzb360 can still connect to and monitor deluge, sonarr & radarr.But transdroid can no longer connect to deluge.I suspect some sort of firewall issue related to the SSH install, but I'm not sure where to look...-ChuckOn Jun 2, 2019 11:39 AM, Tom Morgan <notifications@github.com> wrote:@rudolph4404 - Are you sure the Deluge container is fully up and running correctly?
i.e. Can anything connect to Deluge?
I just went into my currently running config and Sonarr and Radarr are connecting fine using the "Test" function under Download Clients.
I'll test them both shortly on a freshly started stack and see how they are with that too.

**Comment by tom472** [comment]
I'd start by disabling the firewall and see if that make things better.

Then more troubleshooting can go from there.

**Comment by rudolph4404** [comment]
The problem is a firewall issue.
After disabling ufw, the sonarr/deluge download client test works. Still testing other functionality.
You might want to add some testing for this into mediabox.sh. See https://linuxize.com/post/how-to-setup-a-firewall-with-ufw-on-ubuntu-18-04/ for more details. You should at least document what needs to be opened up for mediabox to work properly.

**Comment by tom472** [comment]
Do you have any logs from when it wasn't working?

It is still kind of odd that internal services trying to talk to each other were having issues. Unless the FW was having issues with passing traffic between the Docker network and host machine network.

I could probably test/check for ufw status but not sure people would want the script making adjustments to ufw during set-up. I guess I was thinking most people are handling FW via their router/gateway and not necessarily directly on the server running Medaibox.

**Comment by tom472** [comment]
If you are looking for what would need to be open for Mediabox you can run this command from the `mediabox` directory:
`$ cat docker-compose.yml | grep {IP_ADDRESS}`

That will provide a list of all the ports that are used within Mediabox.

Aside form that - Mediabox would not be taking on any sort of firewall configuration(s).

Hope this helps - Thanks
