### ISSUE TITLE
Add bw_plex support

### ISSUE THREAD

**Issue by wibuf** [tom472/mediabox#79]
Is there an easy way to add bw_plex to portainer?
bw_plex is an app that watches plex for tv shows playing, and skips the intro/theme song. 

https://github.com/Hellowlol/bw_plex
Docker install:
docker pull hellowlol/bw_plex

**Comment by tom472** [comment]
It looks like this container is still fairly alpha.
Have you used/tested it?
Has it been working well?

I'll try and spin it up and see how it goes.

**Comment by wibuf** [comment]
Works well enough for the most part. Especially for sitcoms where the intro is the same each episode. Great for binging a series in one sitting.

**Comment by tom472** [comment]
This project still doesn't seem to be ready for primetime - 
Removing as a feature request.
