### ISSUE TITLE
DelugeVPN Container Not Available

### ISSUE THREAD

**Issue by wiinc1** [tom472/mediabox#81]
I seem to have a similar issue as many of the users in this issue thread except the steps suggested didn't work - reference to the closed issue:  https://github.com/tom472/mediabox/issues/34

I'm running Ubuntu 16.04.6 LTS.

I deleted the containers and rebuilt them - didn't resolve the issue.

I have attempted to hit the app via all the ports associated with the app shown in Portainer. Those ports are: 58846, 58946, 8112, 8118.

I have attempted to access Deluge via the MuxiMuxi homepage for all the apps, but I receive a Page Not Found message.

Portainer shows the container as "running"

In the logs access via Portainer I see something similar to one of the other users. Below is a snippet of the logs:

```
2019-06-15 18:18:22,029 DEBG 'start-script' stdout output:
[warn] PIA endpoint 'nl.privateinternetaccess.com' is not in the list of endpoints that support port forwarding, DL/UL speeds maybe slow
[info] Please consider switching to one of the endpoints shown below
2019-06-15 18:18:22,029 DEBG 'start-script' stdout output:
[info] List of PIA endpoints that support port forwarding:-
[info] ca-toronto.privateinternetaccess.com
[info] ca-montreal.privateinternetaccess.com
[info] ca-vancouver.privateinternetaccess.com
[info] de-berlin.privateinternetaccess.com
[info] de-frankfurt.privateinternetaccess.com
[info] sweden.privateinternetaccess.com
[info] swiss.privateinternetaccess.com
[info] france.privateinternetaccess.com
[info] czech.privateinternetaccess.com
[info] spain.privateinternetaccess.com
2019-06-15 18:18:22,029 DEBG 'start-script' stdout output:
[info] ro.privateinternetaccess.com
[info] israel.privateinternetaccess.com
2019-06-15 18:18:22,043 DEBG 'start-script' stdout output:
[info] Attempting to curl http://209.222.18.222:2000/?client_id=e2bcb73116a606e59e963f97f1a0fd410f64bf79c6739fc869b4ace86ce219ae...
2019-06-15 18:18:22,150 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 12 retries left
[info] Retrying in 10 secs...
2019-06-15 18:18:32,271 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 11 retries left
[info] Retrying in 10 secs...
2019-06-15 18:18:42,399 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 10 retries left
2019-06-15 18:18:42,400 DEBG 'start-script' stdout output:
[info] Retrying in 10 secs...
2019-06-15 18:18:52,531 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 9 retries left
2019-06-15 18:18:52,531 DEBG 'start-script' stdout output:
[info] Retrying in 10 secs...
2019-06-15 18:19:02,655 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
2019-06-15 18:19:02,655 DEBG 'start-script' stdout output:
[info] 8 retries left
[info] Retrying in 10 secs..
2019-06-15 18:19:12,783 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 7 retries left
[info] Retrying in 10 secs...
2019-06-15 18:19:22,912 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 6 retries left
[info] Retrying in 10 secs...
2019-06-15 18:19:33,039 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 5 retries left
[info] Retrying in 10 secs...
2019-06-15 18:19:43,169 DEBG 'start-script' stdout output:
[warn] Response code 000 from curl != 2xx
[warn] Exit code 7 from curl != 0
[info] 4 retries left
[info] Retrying in 10 secs...
```
What have I done wrong ;) ?

**Comment by tom472** [comment]
Can you try a different VPN endpoint and see if that works?

I may need to recheck the list of PIA endpoints that allow port-forwarding.

**Comment by tom472** [comment]
Yeah looks like the Netherlands location has a known issue and may not actually be a port-forwarding endpoint.

https://www.privateinternetaccess.com/forum/discussion/33397/netherlands-now-back-on-the-list-of-port-forward-enabled-endpoints-but-it-doesnt-work

**Comment by wiinc1** [comment]
One of the other steps I did before posting was to run the below command in the containers terminal 

`curl ifconfig.me`

Which gave a different IP (212.XXXXXX) ... I guess that gave me a false sense that everything worked when initially setup.

**Comment by wiinc1** [comment]
I went back through the initial setup shell script and changed the PIA to a different location and that appears to have resolved the issue.

Thanks for all the help and quick replies.

Out of curiosity... If there is not a connection to PIA established between the deluge container and PIA's server, how does Deluge know that it shouldn't download?

**Comment by tom472** [comment]
I believe that the Deluge VPN container has a built in check to verify that it has a valid tunnel established before it passes any traffic.
