### ISSUE TITLE
Known issue with Radarr

### ISSUE THREAD

**Issue by tom472** [tom472/mediabox#84]
Looks like Radarr has an issue connecting to DelugeVPN after DelugeVPN's recent update.

Issue is with Radarr is being tracked via this thread: 
https://github.com/Radarr/Radarr/issues/3562

As soon as its is fixed there it shouldn't take too long for it to make it to the container.

**Comment by Zeds112** [comment]
Apparently the nightly has a fix implemented. What are the best steps to get it with mediabox?

**Comment by tom472** [comment]
So with it being in the nightly I am hoping it will not take to long to get pushed to the master - once that happens Ouroboros should pick it up and things will be good.

As an interim fix you can run these commands from the Mediabox directory:
`$ docker rm -f radarr > /dev/null 2>&1`
`$ perl -i -pe "s/linuxserver\/radarr/linuxserver\/radarr:nightly/" docker-compose.yml`
`$ docker-compose up -d --remove-orphans`

That will change the image being pulled for Radarr from the default 'latest' tag to the 'nightly' tag then relaunch the stack.

**Comment by Zeds112** [comment]
Thanks, I’ll give that a go.

**Comment by Zeds112** [comment]
That works great 👍

**Comment by Curtman** [comment]
> That will change the image being pulled for Radarr from the default 'latest' tag to the 'nightly' tag then relaunch the stack.

Thanks very much for your work tom472.  Sorry if this isn't a great place to ask, but this solution worked well for me, except that I've been using your script somewhat hackishly..  My media is spread across two RAIDS with a tree that looks like foo/TV, foo/Movies, and bar/TV, bar/Movies, so I have been adding those to the containers that need access to them manually in Portainer.

Is there a better way to do this so that re-running the script or this type of fix doesn't make the containers forget about those volumes that I've added?

**Comment by tom472** [comment]
@Curtman Just an FYI I'm out of town briefly for the holiday.  I'll get back to this thread soon.
Thanks
Tom

**Comment by tom472** [comment]
@Curtman Thanks for using Mediabox, sorry for the issue you are having.

I guess I never really thought people would have multiple TV or Movies folders.

Is there any chance you can spread across the RAID by media type i.e.:
`foo\TV`
`bar\Movies`

That way the different data are at different locations but still only one TV and one Movies folder.

Or you might have to use some symlinks or something like that - 
The way Mediabox is configured now is for one (1) individual folder of each media type.

Thanks
--Tom

**Comment by tom472** [comment]
Since there have been several issues with the new version of Deluge (2.0.3) I have rolled back the DelugeVPN container to the 1.3.15 release via this [commit](https://github.com/tom472/mediabox/commit/27e53eaa86461aa258abafb129c9b4212f829f31).

Many of the issues are not showing as scheduled to be fixed until the 2.1 Deluge release.
I will be revisiting any Deluge 2.x issues once the 2.1 release is available.

**Comment by Curtman** [comment]
> @Curtman Thanks for using Mediabox, sorry for the issue you are having.
> 
> I guess I never really thought people would have multiple TV or Movies folders.
> 
> Is there any chance you can spread across the RAID by media type i.e.:
> `foo\TV`
> `bar\Movies`
> 
> That way the different data are at different locations but still only one TV and one Movies folder.
> 
> Or you might have to use some symlinks or something like that -
> The way Mediabox is configured now is for one (1) individual folder of each media type.
> 
> Thanks
> --Tom

The situation came about when I began transitioning to a RAID with larger capacity drives, but they exist with media from two different people now.  Both RAIDs are very large and not easy to combine.  It's not a huge deal to have to re add the volumes to the containers again, other than that it works quite well.  I'm sure I could script it if I was more familiar with docker.  I just wondered if there was an easier way to deal with the concept of multiple TV and multiple Movie folders.  sonarr/radarr/plex/etc seem to deal with them well.

**Comment by cthog** [comment]
Tom, you may want to consider just switching over to qbittorrentvpn, also by BinHex.  I struggled along last night, trying to get Deluge to save my settings (Sonarr won't work correctly if the docker folders don't match (i.e. completed downloads identified as "/data/completed" in both deluge and sonarr containers.)  Deluge *would not* preserve my preference (settings) changes (including activating plugins), no matter how I made them.  Switched browsers, went in and edited .conf file manually... nothing worked.  Switched to qbittorrentvpn with PIA and no issues from the get-go.

**Comment by tom472** [comment]
I can take a look into this and see how it fits.
Thanks for the suggestion.

**Comment by tom472** [comment]
The Deluge issue appears to have been fixed and thus using a current version of the DelugeVPN container appears to be working.
Adjusted in commit: https://github.com/tom472/mediabox/commit/0cf6f52281f72a63f2061d81fe4fef1c32424b26
