### ISSUE TITLE
DelugeVPN not downloading to specified download folder

### ISSUE THREAD

**Issue by Zeds112** [tom472/mediabox#85]
In the ./mediabox.sh setup I’ve specified a downloads folder on an external HDD but DelugeVPN is downloading to the /home/nobody/downloads container folder on my OS drive.

I’ve tried mounting the HDD folder to /home/nobody/downloads but Deluge doesn’t download the files, it just hangs on ‘Downloading’ and no files are created on my HDD.

Any idea how to fix this?

**Comment by tom472** [comment]
Did you check the Troubleshooting section on the Welcome to Mediabox page?
Do the values shown there from your `.env` file settings look correct?

Can you paste the settings listed there from your `.env` file here?

**Comment by Zeds112** [comment]
Yeah the settings all look fine. It seems the files get moved to the downloads folder once they've finished, but they don't download directly to the downloads folder. Is that how it's supposed to work?

```
LOCALUSER=zeds
HOSTNAME=zeds
IP_ADDRESS=192.168.0.50
PUID=1000
PGID=1000
DOCKERGRP=999
PWD=/home/zeds/Documents/mediabox
DLDIR=/media/mount/MediaBox/MediaBoxDownloads
TVDIR=/media/mount/Video/TV Shows/1080p/MP4/TV Shows
MOVIEDIR=/media/mount/Video/All/1080/1080p30
MUSICDIR=/media/mount/MediaBox/MediaBoxMusic
CIDR_ADDRESS=192.168.0.0/24
TZ=Europe/London
PMSTAG=public
PMSTOKEN=
PORTAINERSTYLE=--no-auth
VPN_REMOTE=france.privateinternetaccess.com
CPDAEMONUN=zeds
CPDAEMONPASS=zeds
NZBGETUN=zeds
```

**Comment by tom472** [comment]
Download directory:
i.e. `DLDIR=/media/mount/MediaBox/MediaBoxDownloads`

Represents a top level folder for Download Actions -- there should be (several) sub-folders in there: 
`completed` and `incomplete` would be where the downloads are "going to" depending on their status of in-progress/completion.

Then they get moved to the correct media type folder: `tv`, `movies`, `music`

Is that working for you?

**Comment by Zeds112** [comment]
Yep there are these folders:

`completed  incomplete nzb  queue tmp`

There are some completed files in the completed folder which seems to be working fine but there's nothing in the incomplete folder. Do I need to change any of the Deluge settings in the WebGUI?

**Comment by tom472** [comment]
Is there currently anything in-progress downloading?
If not then incomplete will be empty.

As for the Deluge WebGUI you will need to set a level for the ratio of seeding to stop so the file(s) can then be moved. They will not get moved while still in use. (i.e. seeding)

**Comment by tom472** [comment]
Hey @Zeds112 -- How are things looking?

Things OK yet or still issues?

**Comment by Zeds112** [comment]
Still having issues unfortunately. Did a fresh install of Ubuntu 18.04 today and Deluge still keeps downloading directly into the Docker container folder on my SSD OS drive instead of the HDD download folder I specified. 

I even tried moving the whole root Docker folder to my HDD using the following guide but NTFS drives are not supported for that:
https://stackoverflow.com/questions/50707738/move-docker-var-run-docker-data-to-different-directory

Not sure what to try next. Having a think.

**Comment by tom472** [comment]
When you say this:

> Deluge still keeps downloading directly into the Docker container folder on my SSD OS drive

Do you mean its actually downloading into the actual container - or is it saving to a (wrong) spot but on your host?

**Comment by Zeds112** [comment]
I mean it's downloading into the actual container folder - it's not downloading it to the 'incomplete' folder in my specified download folder.

My download folder is:
/media/mount/MediaBox/MediaBoxDownloads

This folder is empty:
![image](https://user-images.githubusercontent.com/28687745/60302417-c6d4f780-992b-11e9-96db-c25ff8c14f7c.png)

Instead the files are actively being downloaded to the container folder:
![image](https://user-images.githubusercontent.com/28687745/60302547-04d21b80-992c-11e9-86ac-e88267405eda.png)

**Comment by Zeds112** [comment]
Woops seems the screen grab failed, 1 sec

**Comment by tom472** [comment]
Can you add a screenshot from Portainer so I can check something?
Open Portainer - Go to Containers - then click on Delugevpn and take a screenshot of the "Volumes" section. It will be near the bottom.

**Comment by Zeds112** [comment]
Sorry was snoozing. Here:
![image](https://user-images.githubusercontent.com/28687745/60340129-a7c57c80-99a2-11e9-8038-767265bbe91e.png)

**Comment by tom472** [comment]
OK let's see if any of those mappings working?

Can you run this:
`$ docker exec -it delugevpn /bin/sh -c "touch /config/test_config_mount.txt"`
Do you end up with a file called `test_config_mount.txt` in your host `/home/zeds/Doumnets/mediabox/delugevpn/config` folder?

And then try:
`$ docker exec -it delugevpn /bin/sh -c "touch /data/test_data_mount.txt"`
And does that make a file called `test_data_mount.txt` in your host `/media/mount/MediaBox/MediaBoxDownloads` folder?

**Comment by Zeds112** [comment]
Yes both of those work correctly.

**Comment by tom472** [comment]
OK let's check the core.conf file can you run these and paste the output?

From the `medisbox` folder:
`$ cat delugevpn/config/core.conf | grep "download_location"`
and
`$ cat delugevpn/config/core.conf | grep "move_completed_path"`

**Comment by Zeds112** [comment]
Oddly it seems Sonarr also checks in its container /home/nobody/Downloads folder instead of /media/mount/MediaBox/MediaBoxDownloads/completed 

If I add the following to the Sonarr and Deluge sections of the docker-compose.yml then then things seem to start working more correctly:

` - '/media/mount/MediaBox/DelugeDownloads:/home/nobody/Downloads'`

Ok I'll try that.

**Comment by Zeds112** [comment]
Here is the output:
```
zeds@zeds-N:~/Documents/mediabox$ cat delugevpn/config/core.conf | grep "download_location"
    "download_location": "/home/nobody/Downloads",
    "download_location_paths_list": [],
zeds@zeds-N:~/Documents/mediabox$ cat delugevpn/config/core.conf | grep "move_completed_path"
    "move_completed_path": "/home/nobody/Downloads",
    "move_completed_paths_list": [],
```

**Comment by tom472** [comment]
OK - there's our problem -- And this one looks like it's on me.
I guess I don't have steps for setting the locations in the Deluge WebUI.

Can you go into the Deluge WebUI and set the "Download to" entry to `/data/incomplete`
And set "Move completed" to `/data/completed`

**Comment by Zeds112** [comment]
Thanks that seems to be working. Do I need to change anything for Sonarr?

**Comment by Zeds112** [comment]
'No' is the answer it seems - Sonarr was just taking a few mins to detect my test file had finished.

Seems all is in order but will post if anything unusual happens. Thanks!

**Comment by tom472** [comment]
Really sorry about that - 
I am going to decide this weekend if I want to just make the change via the script -or- add it to the directions/configs page.

Thanks for hanging in while trying to figure this out.
--Tom
