### ISSUE TITLE
Transferring installation to new computer?

### ISSUE THREAD

**Issue by CarterBrehm** [tom472/mediabox#87]
What would be the best way to transfer the mediabox installation to another computer? I've upgraded my server recently and I don't want to have to reconfigure all of my settings. Since it's all in docker containers, what would I have to do? Is there an easy config file I can copy over as well as my media?

**Comment by tom472** [comment]
Yeah all of your "settings" should be located in the folder(s) on your host PC.
Is your media in your own folder that you used - or - did you let Mediabox set up your Media folders?
Inside the Mediabox folder you should have a directory tree like:

`mediabox`
`├── content`
`├── couchpotato`
`├── delugevpn`
`├── duplicati`
`├── headphones`
`├── historical`
`├── jackett`
`├── jellyfin`
`├── lidarr`
`├── minio`
`├── muximux`
`├── nzbget`
`├── ombi`
`├── ovpn`
`├── plex`
`├── portainer`
`├── radarr`
`├── sickchill`
`├── sonarr`
`└── tautulli`

All you should need to do is copy over those folders inside the `mediabox` folder and re-run the `mediabox.sh` script on the new computer. The script will make adjustments for the new computer and then should bring up the stack using your settings that are in those folders.

I can help provide even more detailed instructions etc. if needed - I first wanted to just basically say that yes it is doable and kind of give an overview.

Let me know 

Thanks
--Tom

**Comment by CarterBrehm** [comment]
What I actually ended up doing was just cloning the drive and putting that in my new server, because just copying over the files and rerunning resulted in Plex complaining about different server details, etc, and I just didn't care. I'm all transferred now though, thanks for the help!
