### ISSUE TITLE
Feature Request:  Step through setup?

### ISSUE THREAD

**Issue by neuman1812** [tom472/mediabox#91]
Not sure if this has been requested,  But could you add a step or select option during install so as to not have multiple things you dont need added?

For instance you have couchpotato and Radarr.  You wouldn't need both.  or Plex if you have it on a different server.

**Comment by tom472** [comment]
I don't have this feature as there is a fairly simple way to address it after the stack is up vs. the amount of code needed to build the logic for a "selective" setup.

All of the containers are launched with the restart "unless-stopped" flag applied.
So all you need to do is after the stack is up is - go into Portainer and "Stop" any container(s) you are not interested in having running. Those selections will even remain in place after updates and reboots etc.

So I have chosen to provide that method for container selection vs. adding it in as selections during config/setup.

Hope that answers your question.

Thanks
--Tom
