### ISSUE TITLE
Stuck on configure

### ISSUE THREAD

**Issue by Lucetia** [tom472/mediabox#94]
I followed the script instructions on the front page and when it gets to the

"Configuring DelugeVPN, NZBGet, Muximux, and Permissions" line it then says
"This may take a few minutes. . . "

24 hours later it is still on this same line with no update.  Any suggestions on what might be causing it?

**Comment by tom472** [comment]
The very next thing that happens requires the DelugeVPN container to have started.
Can you verify that your PIA credentials are correct?

Can you start another terminal session and check the contents of the:
`.env file` that should be in the `mediabox` folder
 
It is a hidden file so to see it you'll need to do and `ls -lah` 
cd to the `mediabox` folder and then `$ cat .env`

**Comment by Lucetia** [comment]
Checked the file and the username and password are correct.   Here is everything that is in the file, if it helps (removed sensitive information)

`###  ------------------------------------------------
###  M E D I A B O X   C O N F I G   S E T T I N G S
###  ------------------------------------------------
###  The values configured here are applied during
###  $ docker-compose up
###  -----------------------------------------------
###  DOCKER-COMPOSE ENVIRONMENT VARIABLES BEGIN HERE
###  -----------------------------------------------
###
LOCALUSER=<username>
HOSTNAME=<password>
IP_ADDRESS=192.168.1.153
PUID=1000
PGID=1000
DOCKERGRP=995
PWD=/home/<username>/mediabox
DLDIR=/home/<username>/downloads
TVDIR=/home/<username>/downloads/tv
MOVIEDIR=/home/<username>/downloads/movies
MUSICDIR=/home/<username>/downloads/music
PIAUNAME=<username>
PIAPASS=<password>
CIDR_ADDRESS=192.168.1.0/24
TZ=America/Los_Angeles
PMSTAG=public
PMSTOKEN=
PORTAINERSTYLE=--no-auth
VPN_REMOTE=ca-montreal.privateinternetaccess.com`

**Comment by tom472** [comment]
Can you see if any containers started up?
From the command line can you run this and paste the output:

`$ docker ps --format "table {{.Names}}\t{{.Status}}"`

**Comment by Lucetia** [comment]
Yeah, I've been messing around with it and I think it's because the one the main page is linked to is 64 bit and the processor in my machine that I'm using is 32 bit.

Found another method to install it and doing that now.  Will update once that is that.  So far it looks like my mistake for not catching that when you asked to do the docker-compose-v test on the front page that the error was there then.

**Comment by tom472** [comment]
I'm actually re-writing that line maybe you can test it for me .. can you try this:

`$ curl -s https://api.github.com/repos/docker/compose/releases/latest | grep "browser_download_url" | grep -m1 `uname -s`-`uname -m` | cut -d '"' -f4 | xargs sudo curl -L -o /usr/local/bin/docker-compose`

That should get the right version for any type of device.

Then run the:
`$ sudo chmod +x /usr/local/bin/docker-compose`
command.

**Comment by Lucetia** [comment]
Sure.  I'll test it out a bit later tonight.  Reformatting the OS and starting fresh so I can test it without any interference of the things I was messing with

**Comment by tom472** [comment]
Gotcha -- sounds good.

**Comment by Lucetia** [comment]
Just to make sure I had it right, replace the `sudo curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose`
with the `$ curl -s https://api.github.com/repos/docker/compose/releases/latest | grep "browser_download_url" | grep -m1 `uname -s`-`uname -m` | cut -d '"' -f4 | xargs sudo curl -L -o /usr/local/bin/docker-compose`

**Comment by tom472** [comment]
Did you happen to grab it before I fixed it to include the backticks in the command?

**Comment by Lucetia** [comment]
Nope, I think I was too slow when I saw it earlier.  The one I saw was that I see now, but apparently looking at what I copied/pasted it looks like it's omitting the `, but it's a copy/paste from what you wrote and it's putting in the `

**Comment by tom472** [comment]
OK I'll have to work on that command.

Can you follow the two commands here to get docker-compose:

https://github.com/docker/compose/releases/tag/1.25.1

Reminder you will need to `sudo` that second line with the `chmod` command.

**Comment by Lucetia** [comment]
If I do those two commands the first time I typed the:

> curl -L https://github.com/docker/compose/releases/download/1.25.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

It gave me curl: (23) Failed writing body (0 != 9) and I had to retype it with sudo at the start and it worked.

After doing the `sudo chmod +x /usr/local/bin/docker-compose` I followed it by `docker-compose -v` and got the same line 1: Not: command not found error.  I think it's mainly because their github defaults to install 64 bit rather than 32 bit (armhf).

In order to get docker compose to install I had to replace #3 on the front page with the following:

`sudo pip install docker-compose`

and then it would start to download.  Though if going that route you might need additional dependencies and found it was suggested to do the following:

`sudo apt-get install libffi-dev libssl-dev && sudo apt-get install -y python python-pip && sudo apt-get remove python-configparser` which was split into 3 different lines, but I just merged it into one.  This installed `docker-compose version 1.25.1, build a82fef0` so looks like it's slightly behind the branch on their github.

After replacing step 3 was able to continue with step 4 and I'm on the part of the script where it is pulling and launching the containers.  Will update as it advances.

**Comment by Lucetia** [comment]
Alright, now an even weirder issue.  I have the device connected to the internet via WIFI and after it starts installing the containers it disconnect my wifi adapters and the system says it can no longer find any.  The first time it locked up during startup and I had to unplug and reboot.  Did that and restarted the script and it was starting up each container and then as it got done it gave an error for nbzget saying the port was already allocated (was showing two nbzget containers), but after it killed the wifi. Went to try and connect and now it says no adapters until I reboot.

**Comment by tom472** [comment]
What type of device are you trying to run this on?

I am not sure this project as a whole will work on/for 32-bit systems.

**Comment by Lucetia** [comment]
> What type of device are you trying to run this on?
> 
> I am not sure this project as a whole will work on/for 32-bit systems.

Right now I was trying to run it off a Raspbian and prior Ubuntu 16.04 and was struggling to get it to work with either.  The processor does support 64 bit, but they suggest 32 bit for it so I might try Ubuntu 16.04 64 bit again and see how it goes.  The problem I had with it was just getting a VNC to go as I prefer messing with it that way rather than hooking up another monitor to it.

**Comment by tom472** [comment]
@Lucetia Are you still trying to get this going?
Can I close this issue?
