### ISSUE TITLE
nginx reverse proxy, certificates

### ISSUE THREAD

**Issue by Bramblefoot** [tom472/mediabox#95]
I setup mediabox and I think it's been going fairly well so far. 
I have what I think is a complicated setup. 
I'm running Windows 10 Pro pc, and under that I am running a virtualbox Ubuntu 18.04 vm, and in that vm I'm running mediabox. Think about that....I'll wait. LoL

Win10Pro (plex is here, 192.168.xxx.xxx)
↳ Ubuntu 18.04 VM (bridged also 192.168.xxx.xxx)
   ↳  Mediabox Containers (bridged 172.16.xxx.xxx)

Here are a couple things I've struggled with, and would like your input on:

- I was wondering if you have considered adding a nginx reverse proxy container to the mix? (I thought I saw nginx on the muximux container) I actually added one myself. I had to stop the muximux container due to port usage, and I created a new nginx container running on port 80. I use it as a reverse proxy and access maybe half of the apps externally via subdomains. Having nginx and reverse proxy already setup would be nice. As an example, I'm able to externally access ombi at: http://ombi.mydomain.com or Tautulli at http://plexdata.mydomain.com

- In my setup I have plex running on the win10Pro pc. I do this because I want to be able to use hardware acceleration. 2 things here - 1. Is it possible to use the plex container from mediabox and still be able to hardware transcode in plex?(its understandable if this is not possible due to hardware virtualization) and 2. I pointed muximux plex config to the ip:port of plex on the win10Pro host but plex never loads externally. I assume this is because of the networking of a container running in a vm. Any ideas on how to get that working? All the containers run on a bridged network to my VM host, which is itself on a bridged network to the win10Pro host. weird, i know.

- Certificates. Where do I setup Let's Encrypt? On the VM hosting the containers? On the nginx reverse proxy container? I'd like to be able to access any of the containers over https externally. Specifically plex.mydomain.com(i think its a good idea to secure that traffic from my provider) 

Thanks,
Bill

**Comment by tom472** [comment]
Closing this as it is beyond the scope of the purpose of this product.
The only item that should be necessary to reach externally is Plex which generally works right out of the box.
