### ISSUE TITLE
Connection not secure error

### ISSUE THREAD

**Issue by rudolph4404** [tom472/mediabox#97]
Today I started getting a "connection not secure" error when trying to bring up mediabox in my browser.
This is happening in both Firefox and Chrome.
I am using Ubuntu 18.04 LTS. All current patches have been installed.
I did try rebooting and clearing the cookies and cache.
Somewhat surprisingly, if I include the port number in the URL I can get to deluge.

**Comment by tom472** [comment]
Well it is not being run with a certificate so it is not "secure" as in running over https.
Is that the type of error you are referring to?
