### ISSUE TITLE
Deluge Failing to connect

### ISSUE THREAD

**Issue by JJR12** [tom472/mediabox#99]
Hey Tom great set up you made.  I've been using it for a while with absolutely 0 issues until today.  I just updated mediabox (./mediabox.sh) and now deluge is giving me an. error that its failing to connect any ideas?

Thank you

**Comment by Bramblefoot** [comment]
I also recently had an issue with delugevpn container. I could not connect
to the delugevpn UI. If this is your issue, continue reading.

I found out that during startup, a script was failing. The setting
STRICT_PORT_FORWARD was set to yes, however the server I picked must have
stopped allowing port forwarding. This caused the container startup to
error, never allowing the delugevpn UI to start. I changed that setting to
no and restarted the container. It worked immediately.
I'm not sure if this is your issue. Hope this info helps.

Cheers,
Bill

**Comment by JJR12** [comment]
@Bramblefoot  thank you for the help!

While looking at the logs its the port forwarding for sure but after digging around on the PIA forum it seems like all the CA and France servers are down in regards to port forwarding so while your solution worked, I found that when configuring you could also select a different server that has port forwarding up and running in my case it was the frankfurt one.

**Comment by tom472** [comment]
@JJR12 @Bramblefoot 
Thanks to both of you for bringing of this issue and finding solutions.
Glad it was more or less a issue with PIA's port forwarding server(s) and that appears to be corrected now.

**Comment by tom472** [comment]
Re-Opening until CA servers are resolved as well.
